#ifndef _INIT_IMAGES_H
#define _INIT_IMAGES_H


#define _PLAYER_COLOR COLOR_CYAN
#define _GHOST_COLOR COLOR_WHITE
#define _DEAD_GHOST_COLOR COLOR_RED
#define _SKULL_COLOR COLOR_YELLOW
#define _BOMB_COLOR COLOR_RED
#define _MISSILE_COLOR COLOR_WHITE
#define _ROCKET_COLOR COLOR_WHITE
#define _POWERUP_COLOR COLOR_GREEN
#define _FREEZE_COLOR COLOR_CYAN
#define _SUPER_COLOR COLOR_RED
#define _GUN_COLOR COLOR_PURPLE
#define _BULLET_COLOR COLOR_WHITE
#define _BRICK_COLOR COLOR_YELLOW
#define _EXTRA_POINTS_COLOR COLOR_YELLOW
#define _EXTRA_LIFE_COLOR COLOR_WHITE
#define _INVINCIBILITY_COLOR COLOR_YELLOW
#define _CONFUSE_COLOR COLOR_RED
#define _ZOMBIE_COLOR COLOR_YELLOW


void INIT_IMAGES(void);




#endif // _INIT_IMAGES_H

