#

# COCO_COLOR_GFX_GAME_OPTS ?= -DMAX_ARROWS_ON_SCREEN=7 -DFASTER_WALL_REDRAW -DNUMBER_OF_MISSILES=3

CREATIVISION_GAME_OPTS ?= -DLESS_TEXT

GAMATE_GAME_OPTS ?= -DLESS_TEXT -DNO_BLINKING -DSIMPLE_STRATEGY -DNO_HINTS

C128_Z80_80COL_GAME_OPTS ?=  -DLESS_TEXT -DNO_BLINKING -DNO_HINTS -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=15
    
# ZX81_NO_GFX_GAME_OPTS ?= -DMAX_ARROWS_ON_SCREEN=7 -DNUMBER_OF_MISSILES=4 -DMISSILE_DROP_LOOP_MASK=1 -DSMALL_WALL 

ZX81_GFX_GAME_OPTS ?=  -DLESS_TEXT -DNO_BLINKING -DNO_HINTS -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=15

APPLE2_GAME_OPTS ?= -DMAX_ARROWS_ON_SCREEN=6 -DNUMBER_OF_MISSILES=3 -DLESS_TEXT -DNO_BLINKING -DNO_HINTS -DSIMPLE_STRATEGY

COMX_GAME_OPTS ?= -DNO_BLINKING  -DNO_INITIAL_SCREEN -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=15 -DGHOSTS_NUMBER=7

PECOM_GAME_OPTS ?= -DNO_BLINKING -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=15 -DGHOSTS_NUMBER=7

TMC600_GAME_OPTS ?= -DNO_BLINKING -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=15 -DGHOSTS_NUMBER=7

MICRO_GAME_OPTS ?= -DNO_BLINKING -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=15 -DGHOSTS_NUMBER=7

#__VIC20_EXP_3K_GAME_OPTS ?= -DNO_BLINKING -DNO_HINTS -DLESS_TEXT

CAMPUTERS_LYNX_GAME_OPTS ?= -DNO_BLINKING -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=7 -DGHOSTS_NUMBER=7 -DMAX_ARROWS_ON_SCREEN=7 -DFASTER_WALL_REDRAW -DNUMBER_OF_MISSILES=3

TI99_GAME_OPTS           ?= -DLESS_TEXT -DNO_HINTS -DSIMPLE_STRATEGY -DNO_BLINKING -DBOMB_DRAW_SKIP=3 -DWALL_DRAW_SKIP=7 -DGHOSTS_NUMBER=7 -DMAX_ARROWS_ON_SCREEN=7 -DFASTER_WALL_REDRAW -DNUMBER_OF_MISSILES=3