
// BLUE
#define _PLAYER_DOWN 61
#define _PLAYER_UP 60
#define _PLAYER_RIGHT 63
#define _PLAYER_LEFT 62
#define _PLAYER _PLAYER_DOWN

#define _GUN 0x5B

// YELLOW
#define _SKULL 0x65
#define _VERTICAL_BRICK 0x62
#define _HORIZONTAL_BRICK 0x63
#define _EXTRA_LIFE _PLAYER_DOWN
#define _EXTRA_POINTS 0x6A

// GREEN
#define _POWERUP  0x5D

// RED
#define _BOMB 59

// CYAN
#define _INVINCIBILITY 0x5C
#define _BULLET 0x61

#define _CONFUSE _SKULL

#define _BROKEN_BRICK _BOMB

// WHITE
#define _GHOST 58

#define _DEAD_GHOST _GHOST

#define _LEFT_HORIZONTAL_MISSILE 0x5F

#define _RIGHT_HORIZONTAL_MISSILE 0x7A

#define _ROCKET 0x5E

