

// LEVEL 2

#define LV_CROSS_OFFSET XSize/3


#if XSize>40
    #define LV_CROSS_WIDTH XSize/7

#elif XSize>=20 && YSize>=16
    #define LV_CROSS_WIDTH XSize/5
    
#else
    #define LV_CROSS_WIDTH (LV_CROSS_OFFSET-2)
#endif


#if YSize>=22
    #define LV_CROSS_HEIGHT YSize/4
#else
    #define LV_CROSS_HEIGHT YSize/5
#endif


#if XSize>=20 && YSize>=17

    #define LV_CROSS_NO_OF_OBJECTS 30

    #define LV_CROSS_OBJECTS \
        LV_CROSS_NO_OF_OBJECTS, \
        \
        LV_CROSS_OFFSET,4,1,LV_CROSS_HEIGHT,WALL, \
        XSize-1-LV_CROSS_OFFSET,4,1,LV_CROSS_HEIGHT,WALL, \
        \
        LV_CROSS_OFFSET,YSize-4-LV_CROSS_HEIGHT,1,LV_CROSS_HEIGHT+1,WALL, \
        XSize-1-LV_CROSS_OFFSET,YSize-4-LV_CROSS_HEIGHT+1,1,LV_CROSS_HEIGHT,WALL, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,4+LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        XSize-1-LV_CROSS_OFFSET,4+LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,YSize-4-LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        XSize-1-LV_CROSS_OFFSET,YSize-4-LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        \
        \
        LV_CROSS_OFFSET+1+1,YSize-4-LV_CROSS_HEIGHT+1+2,2,1,BLOCK, \
        LV_CROSS_OFFSET+1+1,4+LV_CROSS_HEIGHT-1-2   ,2,1,BLOCK, \
        LV_CROSS_OFFSET+1+1+XSize-2*(LV_CROSS_OFFSET)-6,YSize-4-LV_CROSS_HEIGHT+1+2,2,1,BLOCK, \
        LV_CROSS_OFFSET+1+1+XSize-2*(LV_CROSS_OFFSET)-6,4+LV_CROSS_HEIGHT-1-2   ,2,1,BLOCK, \
        \
        \
        LV_CROSS_OFFSET+1+1+2,YSize-4-LV_CROSS_HEIGHT+1+2,XSize-2U*(LV_CROSS_OFFSET)-8U,1,WALL, \
        LV_CROSS_OFFSET+1+1+2,4+LV_CROSS_HEIGHT-1-2   ,XSize-2U*(LV_CROSS_OFFSET)-8U,1,WALL, \
        \
        LV_CROSS_OFFSET-1,4,1,LV_CROSS_HEIGHT,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+1,4,1,LV_CROSS_HEIGHT,DIAMOND, \
        \
        LV_CROSS_OFFSET-1,YSize-4-LV_CROSS_HEIGHT+1,1,LV_CROSS_HEIGHT,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+1,YSize-4-LV_CROSS_HEIGHT+1,1,LV_CROSS_HEIGHT,DIAMOND, \
        \
        XSize-2,2,1,1,FREEZE, \
        XSize-2,YSize-2,1,1,RING, \
        \
        1,2,1,1,RING, \
        1,YSize-2,1,1,FREEZE, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,4+LV_CROSS_HEIGHT-1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+2,4+LV_CROSS_HEIGHT-1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,YSize-4-LV_CROSS_HEIGHT+1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+2,YSize-4-LV_CROSS_HEIGHT+1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        \
        LV_CROSS_OFFSET+1,4,1,LV_CROSS_HEIGHT+1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET-1,4,1,LV_CROSS_HEIGHT+1,DIAMOND, \
        \
        LV_CROSS_OFFSET+1,YSize-4-LV_CROSS_HEIGHT,1,LV_CROSS_HEIGHT+1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET-1,YSize-4-LV_CROSS_HEIGHT,1,LV_CROSS_HEIGHT+1,DIAMOND \
        \

#else

    #define LV_CROSS_NO_OF_OBJECTS 28

    #define LV_CROSS_OBJECTS \
        LV_CROSS_NO_OF_OBJECTS, \
        \
        LV_CROSS_OFFSET,4,1,LV_CROSS_HEIGHT,WALL, \
        XSize-1-LV_CROSS_OFFSET,4,1,LV_CROSS_HEIGHT,WALL, \
        \
        LV_CROSS_OFFSET,YSize-4-LV_CROSS_HEIGHT,1,LV_CROSS_HEIGHT+1,WALL, \
        XSize-1-LV_CROSS_OFFSET,YSize-4-LV_CROSS_HEIGHT+1,1,LV_CROSS_HEIGHT,WALL, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,4+LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        XSize-1-LV_CROSS_OFFSET,4+LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,YSize-4-LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        XSize-1-LV_CROSS_OFFSET,YSize-4-LV_CROSS_HEIGHT,LV_CROSS_WIDTH,1,WALL, \
        \
        \
        LV_CROSS_OFFSET+1+1,YSize-4-LV_CROSS_HEIGHT+1+2,2,1,BLOCK, \
        LV_CROSS_OFFSET+1+1,4+LV_CROSS_HEIGHT-1-2   ,2,1,BLOCK, \
        LV_CROSS_OFFSET+1+1+XSize-2*(LV_CROSS_OFFSET)-6,YSize-4-LV_CROSS_HEIGHT+1+2,2,1,BLOCK, \
        LV_CROSS_OFFSET+1+1+XSize-2*(LV_CROSS_OFFSET)-6,4+LV_CROSS_HEIGHT-1-2   ,2,1,BLOCK, \
        \
        \
        \
        LV_CROSS_OFFSET-1,4,1,LV_CROSS_HEIGHT,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+1,4,1,LV_CROSS_HEIGHT,DIAMOND, \
        \
        LV_CROSS_OFFSET-1,YSize-4-LV_CROSS_HEIGHT+1,1,LV_CROSS_HEIGHT,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+1,YSize-4-LV_CROSS_HEIGHT+1,1,LV_CROSS_HEIGHT,DIAMOND, \
        \
        XSize-2,2,1,1,FREEZE, \
        XSize-2,YSize-2,1,1,RING, \
        \
        1,2,1,1,RING, \
        1,YSize-2,1,1,FREEZE, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,4+LV_CROSS_HEIGHT-1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+2,4+LV_CROSS_HEIGHT-1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        \
        LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,YSize-4-LV_CROSS_HEIGHT+1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET+2,YSize-4-LV_CROSS_HEIGHT+1,LV_CROSS_WIDTH-2,1,DIAMOND, \
        \
        LV_CROSS_OFFSET+1,4,1,LV_CROSS_HEIGHT+1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET-1,4,1,LV_CROSS_HEIGHT+1,DIAMOND, \
        \
        LV_CROSS_OFFSET+1,YSize-4-LV_CROSS_HEIGHT,1,LV_CROSS_HEIGHT+1,DIAMOND, \
        XSize-1-LV_CROSS_OFFSET-1,YSize-4-LV_CROSS_HEIGHT,1,LV_CROSS_HEIGHT+1,DIAMOND \
        \
    

#endif


#define LV_CROSS_OBJECTS_SIZE LV_OBJECTS_SIZE(LV_CROSS_NO_OF_OBJECTS)


//


#if !defined(FEWER_SHURIKENS)
    #define LV_CROSS_SHURIKENS \
        4,4,2, \
        2,2,\
        XSize-3,3, \
        2,YSize-2, \
        XSize-3,YSize-3, \
        \
        LV_CROSS_OFFSET-3,2, \
        XSize-1-LV_CROSS_OFFSET+3,2, \
        LV_CROSS_OFFSET-3,YSize-2, \
        XSize-1-LV_CROSS_OFFSET+3,YSize-2, \
        \
        2, \
        XSize-3
    #define LV_CROSS_SHURIKENS_SIZE LV_SHURIKENS_SIZE(4,4,2)

#else
    #define LV_CROSS_SHURIKENS \
        2,2,2, \
        2,2,\
        XSize-3,YSize-3, \
        \
        LV_CROSS_OFFSET-3,2, \
        XSize-1-LV_CROSS_OFFSET+3,YSize-2, \
        \
        2, \
        XSize-3
    #define LV_CROSS_SHURIKENS_SIZE LV_SHURIKENS_SIZE(2,2,2)

#endif    




#define LV_CROSS_NO_OF_WALLS 4

#define LV_CROSS_WALLS \
    LV_CROSS_NO_OF_WALLS, \
    LV_CROSS_OFFSET+1+1,YSize-4-YSize/4+1, \
    XSize-2*(LV_CROSS_OFFSET)-4,1,\
    \
    LV_CROSS_OFFSET+1+1,4+YSize/4-1,\
    XSize-2*(LV_CROSS_OFFSET)-4,1,\
    \
    LV_CROSS_OFFSET-LV_CROSS_WIDTH+1,4+YSize/4+1,\
    1,YSize-9-2*(YSize/4),\
    \
    XSize-1-LV_CROSS_OFFSET+LV_CROSS_WIDTH-1,4+YSize/4+1,\
    1,YSize-9-2*(YSize/4)

#define LV_CROSS_WALLS_SIZE LC_WALLS_SIZE(LV_CROSS_NO_OF_WALLS)


