#include "cross_lib.h"
#include "screen_types.h"

// ------------------------------------------------------------
// Helper macros to compute sizes and offsets
#define LV_OBJECTS_SIZE(no_of_rect) (1+(no_of_rect*5))

#define LV_SHURIKENS_SIZE(horiz,vert,mini) (1+(horiz)*2+ 1+(vert)*2+ 1+(mini))

#define LC_WALLS_SIZE(walls) (1+(walls*4))
//

#include "level_horiz.h"
#include "level_vert_bars.h"
#include "level_rain.h"
#include "level_h_barriers.h"
#include "level_cross.h"
#include "level_horiz_walls.h"
#include "level_squares.h"
#include "level_many.h"
#include "level_vert_walls.h"

// LEVEL 0 - Lots of horizontal shurikens
#define LV_0_OBJECTS LV_HORIZ_OBJECTS
#define LV_0_OBJECTS_SIZE LV_HORIZ_OBJECTS_SIZE
#define LV_0_SHURIKENS LV_HORIZ_SHURIKENS
#define LV_0_SHURIKENS_SIZE LV_HORIZ_SHURIKENS_SIZE
#define LV_0_WALLS LV_HORIZ_WALLS 
#define LV_0_WALLS_SIZE LV_HORIZ_WALLS_SIZE

// LEVEL 1 - Vertical walls
#define LV_1_OBJECTS LV_VERT_BARS_OBJECTS
#define LV_1_OBJECTS_SIZE LV_VERT_BARS_OBJECTS_SIZE
#define LV_1_SHURIKENS LV_VERT_BARS_SHURIKENS
#define LV_1_SHURIKENS_SIZE LV_VERT_BARS_SHURIKENS_SIZE
#define LV_1_WALLS LV_VERT_BARS_WALLS 
#define LV_1_WALLS_SIZE LV_VERT_BARS_WALLS_SIZE

// LEVEL 2 - Rain
#define LV_2_OBJECTS LV_RAIN_OBJECTS
#define LV_2_OBJECTS_SIZE LV_RAIN_OBJECTS_SIZE
#define LV_2_SHURIKENS LV_RAIN_SHURIKENS
#define LV_2_SHURIKENS_SIZE LV_RAIN_SHURIKENS_SIZE
#define LV_2_WALLS LV_RAIN_WALLS 
#define LV_2_WALLS_SIZE LV_RAIN_WALLS_SIZE

// LEVEL 3 - horizontal barriers
#define LV_3_OBJECTS LV_H_BARRIERS_OBJECTS
#define LV_3_OBJECTS_SIZE LV_H_BARRIERS_OBJECTS_SIZE
#define LV_3_SHURIKENS LV_H_BARRIERS_SHURIKENS
#define LV_3_SHURIKENS_SIZE LV_H_BARRIERS_SHURIKENS_SIZE
#define LV_3_WALLS LV_H_BARRIERS_WALLS 
#define LV_3_WALLS_SIZE LV_H_BARRIERS_WALLS_SIZE

// LEVEL 4 - cross
#define LV_4_OBJECTS LV_CROSS_OBJECTS
#define LV_4_OBJECTS_SIZE LV_CROSS_OBJECTS_SIZE
#define LV_4_SHURIKENS LV_CROSS_SHURIKENS
#define LV_4_SHURIKENS_SIZE LV_CROSS_SHURIKENS_SIZE
#define LV_4_WALLS LV_CROSS_WALLS 
#define LV_4_WALLS_SIZE LV_CROSS_WALLS_SIZE

// LEVEL 5 - horiz wall
#define LV_5_OBJECTS LV_HORIZ_WALLS_OBJECTS
#define LV_5_OBJECTS_SIZE LV_HORIZ_WALLS_OBJECTS_SIZE
#define LV_5_SHURIKENS LV_HORIZ_WALLS_SHURIKENS
#define LV_5_SHURIKENS_SIZE LV_HORIZ_WALLS_SHURIKENS_SIZE
#define LV_5_WALLS LV_HORIZ_WALLS_WALLS 
#define LV_5_WALLS_SIZE LV_HORIZ_WALLS_WALLS_SIZE

// LEVEL 6 - squares
#define LV_6_OBJECTS LV_SQUARES_OBJECTS
#define LV_6_OBJECTS_SIZE LV_SQUARES_OBJECTS_SIZE
#define LV_6_SHURIKENS LV_SQUARES_SHURIKENS
#define LV_6_SHURIKENS_SIZE LV_SQUARES_SHURIKENS_SIZE
#define LV_6_WALLS LV_SQUARES_WALLS 
#define LV_6_WALLS_SIZE LV_SQUARES_WALLS_SIZE

// LEVEL 7 - many
#define LV_7_OBJECTS LV_MANY_OBJECTS
#define LV_7_OBJECTS_SIZE LV_MANY_OBJECTS_SIZE
#define LV_7_SHURIKENS LV_MANY_SHURIKENS
#define LV_7_SHURIKENS_SIZE LV_MANY_SHURIKENS_SIZE
#define LV_7_WALLS LV_MANY_WALLS 
#define LV_7_WALLS_SIZE LV_MANY_WALLS_SIZE

// LEVEL 8 - many
#define LV_8_OBJECTS LV_VERT_WALLS_OBJECTS
#define LV_8_OBJECTS_SIZE LV_VERT_WALLS_OBJECTS_SIZE
#define LV_8_SHURIKENS LV_VERT_WALLS_SHURIKENS
#define LV_8_SHURIKENS_SIZE LV_VERT_WALLS_SHURIKENS_SIZE
#define LV_8_WALLS LV_VERT_WALLS_WALLS 
#define LV_8_WALLS_SIZE LV_VERT_WALLS_WALLS_SIZE

// ----------------------------------------------------------
// Objects: static walls and collectable items
const uint8_t objects_map[] =
{

	LV_0_OBJECTS,
	
	LV_1_OBJECTS,
    
	LV_2_OBJECTS,
	
	LV_3_OBJECTS,
    
    LV_4_OBJECTS,
    
    LV_5_OBJECTS,
	
    LV_6_OBJECTS,
    
    LV_7_OBJECTS,
    
    LV_8_OBJECTS,   

};


const uint16_t objects_index[] = 
{
	0, // level 0
	LV_0_OBJECTS_SIZE, // level 1
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE, // level 2
    0, // level 3 (challenge)
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE, // level 4
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_3_OBJECTS_SIZE, // level 5
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_3_OBJECTS_SIZE+LV_4_OBJECTS_SIZE, // level 6
    0, // level 7 (challenge)
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_3_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE, // level 8
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_3_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE+LV_6_OBJECTS_SIZE, // level 9
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_3_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE+LV_6_OBJECTS_SIZE+LV_7_OBJECTS_SIZE,
    0, // level 11(challenge)
    
    // 0,
    // 1+6*12,
    // 1+6*12+1+6*11,
    // 1+6*12+1+6*11+1+6*12

    // TODO: ....
};


// ----------------------------------------------------------
// Shurikens: horizontal, vertical and mini-shurikens
const uint8_t shurikens_map[] =
{

	LV_0_SHURIKENS,
	
	// level=1
   	LV_1_SHURIKENS,

    // level=2
   	LV_2_SHURIKENS,
        
    // level=3
	LV_3_SHURIKENS,
    
    //
    LV_4_SHURIKENS,
  
    //
    LV_5_SHURIKENS,
	
	//
	LV_6_SHURIKENS,
    
    //
    LV_7_SHURIKENS,
    
    //
    LV_8_SHURIKENS,
    
};


const uint8_t shurikens_index[] = 
{
	0,
	LV_0_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE,
    0,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_3_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_3_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE,
	0,
    LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_3_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_3_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_3_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE+LV_7_SHURIKENS_SIZE,
    // 0,
    // 1+2*12+1+1,
    // 1+2*12+1+1+ 1+2*2+1+1+4*1,
    // 1+2*12+1+1+ 1+2*2+1+1+4*1+ 1+2*2+ 1+4*2+ 1,    
    // TODO: ....
};



// ----------------------------------------------------------
// Walls: dynamic walls
const uint8_t walls_map[] =
{
	LV_0_WALLS,
	LV_1_WALLS,
	LV_2_WALLS,
	LV_3_WALLS,
    LV_4_WALLS,
    LV_5_WALLS,
	LV_6_WALLS,
    LV_7_WALLS,
    LV_8_WALLS,
};

const uint8_t walls_index[] =
{
	0,
	LV_0_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE,
    0, // challenge
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_3_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_3_WALLS_SIZE+LV_4_WALLS_SIZE,
    0, // challenge
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_3_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_3_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_3_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE+LV_7_WALLS_SIZE,
    0, // challenge
    // 0,
    // 1,
    // 1+1+2*8,
};

