
// LEVEL 9 SHOWN AS 10


#if XSize>20
    #define LV_SQUARES_WIDTH (1+(XSize/3))
#elif XSize>16 
	#define LV_SQUARES_WIDTH (1+(XSize/4))
#else
	#define LV_SQUARES_WIDTH XSize/5
#endif

#if YSize>40
    #define LV_SQUARES_HEIGHT YSize/4
#elif YSize>20
    #define LV_SQUARES_HEIGHT YSize/4
#elif YSize>16 
	#define LV_SQUARES_HEIGHT YSize/5
#else
	#define LV_SQUARES_HEIGHT YSize/6
#endif

#define LV_SQUARES_POS ((XSize-LV_SQUARES_WIDTH)/2)

#define LV_SQUARES_NO_OF_OBJECTS 16

#define LV_SQUARES_OBJECTS \
    LV_SQUARES_NO_OF_OBJECTS, \
	\
    LV_SQUARES_POS,2,LV_SQUARES_WIDTH,LV_SQUARES_HEIGHT,WALL, \
    LV_SQUARES_POS,YSize-LV_SQUARES_HEIGHT-1,LV_SQUARES_WIDTH,LV_SQUARES_HEIGHT,WALL, \
	\
    1,2,1,1,RING, \
    XSize-2,2,1,1,RING, \
    \
    LV_SQUARES_POS-1,YSize-2,1,1,FREEZE, \
    LV_SQUARES_POS+LV_SQUARES_WIDTH,YSize-2,1,1,FREEZE, \
    LV_SQUARES_POS-1,2,1,1,FREEZE, \
    LV_SQUARES_POS+LV_SQUARES_WIDTH,2,1,1,FREEZE, \
    \
    LV_SQUARES_POS-4,YSize-LV_SQUARES_HEIGHT-1,3,1,BLOCK, \
    LV_SQUARES_POS+LV_SQUARES_WIDTH+1,YSize-LV_SQUARES_HEIGHT-1,3,1,BLOCK, \
    \
    LV_SQUARES_POS-4,YSize-LV_SQUARES_HEIGHT-1-4,3,1,BLOCK, \
    LV_SQUARES_POS+LV_SQUARES_WIDTH+1,YSize-LV_SQUARES_HEIGHT-1-4,3,1,BLOCK, \
    \
	1,3,1,YSize-4,DIAMOND, \
	XSize-2,3,1,YSize-4,DIAMOND, \
    \
    LV_SQUARES_POS,2+LV_SQUARES_HEIGHT,LV_SQUARES_WIDTH,1,DIAMOND, \
    LV_SQUARES_POS,YSize-LV_SQUARES_HEIGHT-2    ,LV_SQUARES_WIDTH,1,DIAMOND   
    



#define LV_SQUARES_OBJECTS_SIZE LV_OBJECTS_SIZE(LV_SQUARES_NO_OF_OBJECTS)


//


#if XSize>=20
    #define LV_SQUARES_SHURIKENS \
        4,4,4, \
        3,1+2+LV_SQUARES_HEIGHT, \
        XSize-4,YSize-LV_SQUARES_HEIGHT-1-2, \
        XSize-4,1+2+LV_SQUARES_HEIGHT+1, \
        3,YSize-LV_SQUARES_HEIGHT-1-2-1, \
        \
        LV_SQUARES_POS,1+2+LV_SQUARES_HEIGHT, \
        LV_SQUARES_POS+LV_SQUARES_WIDTH-1,YSize-LV_SQUARES_HEIGHT-1-2-1, \
        LV_SQUARES_POS-1,1+2+LV_SQUARES_HEIGHT, \
        LV_SQUARES_POS+1+LV_SQUARES_WIDTH-1,YSize-LV_SQUARES_HEIGHT-1-2-1, \
        \
        LV_SQUARES_POS-2, \
        LV_SQUARES_POS+LV_SQUARES_WIDTH-1+2, \
        2, \
        XSize-1-2    
        
    #define LV_SQUARES_SHURIKENS_SIZE LV_SHURIKENS_SIZE(4,4,4)
#else
    #define LV_SQUARES_SHURIKENS \
        4,4,2, \
        3,1+2+LV_SQUARES_HEIGHT, \
        XSize-4,YSize-LV_SQUARES_HEIGHT-1-2, \
        XSize-4,1+2+LV_SQUARES_HEIGHT+1, \
        3,YSize-LV_SQUARES_HEIGHT-1-2-1, \
        \
        LV_SQUARES_POS,1+2+LV_SQUARES_HEIGHT, \
        LV_SQUARES_POS+LV_SQUARES_WIDTH-1,YSize-LV_SQUARES_HEIGHT-1-2-1, \
        LV_SQUARES_POS-1,1+2+LV_SQUARES_HEIGHT, \
        LV_SQUARES_POS+1+LV_SQUARES_WIDTH-1,YSize-LV_SQUARES_HEIGHT-1-2-1, \
        \
        2, \
        XSize-1-2    
        
    #define LV_SQUARES_SHURIKENS_SIZE LV_SHURIKENS_SIZE(4,4,2)
#endif


#define LV_SQUARES_NO_OF_WALLS 0

#define LV_SQUARES_WALLS \
	LV_SQUARES_NO_OF_WALLS


#define LV_SQUARES_WALLS_SIZE LC_WALLS_SIZE(LV_SQUARES_NO_OF_WALLS)


