#include "cross_lib.h"
#include "screen_types.h"

#if !defined(FEWER_SHURIKENS) && (YSize<=16 || XSize<=16)
    #define FEWER_SHURIKENS
#endif

// ------------------------------------------------------------
// Helper macros to compute sizes and offsets
#define LV_OBJECTS_SIZE(no_of_rect) (1+(no_of_rect*5))

#define LV_SHURIKENS_SIZE(horiz,vert,mini) (1+(horiz)*2+ 1+(vert)*2+ 1+(mini))

#define LC_WALLS_SIZE(walls) (1+(walls*4))
//

#include "level_00_horiz.h"        // level 0
#include "level_01_vert_bars.h"    // level 1
#include "level_02_cross.h"        // level 2

#include "level_04_horiz_walls.h"  // level 4
#include "level_05_h_barriers.h"   // level 5
#include "level_06_rain.h"         // level 6

#include "level_08_vert_walls.h"   // level 8
#include "level_09_squares.h"      // level 9
#include "level_10_many.h"         // level 10

#include "level_03_07_11_boss.h"   // level 3, 7, 11


// Level 0 - shown as 1
#define LV_0_OBJECTS LV_HORIZ_OBJECTS
#define LV_0_OBJECTS_SIZE LV_HORIZ_OBJECTS_SIZE
#define LV_0_SHURIKENS LV_HORIZ_SHURIKENS
#define LV_0_SHURIKENS_SIZE LV_HORIZ_SHURIKENS_SIZE
#define LV_0_WALLS LV_HORIZ_WALLS 
#define LV_0_WALLS_SIZE LV_HORIZ_WALLS_SIZE


// Level 1 - shown as 2
#define LV_1_OBJECTS LV_VERT_BARS_OBJECTS
#define LV_1_OBJECTS_SIZE LV_VERT_BARS_OBJECTS_SIZE
#define LV_1_SHURIKENS LV_VERT_BARS_SHURIKENS
#define LV_1_SHURIKENS_SIZE LV_VERT_BARS_SHURIKENS_SIZE
#define LV_1_WALLS LV_VERT_BARS_WALLS 
#define LV_1_WALLS_SIZE LV_VERT_BARS_WALLS_SIZE

// Level 2 - shown as 3
#define LV_2_OBJECTS LV_CROSS_OBJECTS
#define LV_2_OBJECTS_SIZE LV_CROSS_OBJECTS_SIZE
#define LV_2_SHURIKENS LV_CROSS_SHURIKENS
#define LV_2_SHURIKENS_SIZE LV_CROSS_SHURIKENS_SIZE
#define LV_2_WALLS LV_CROSS_WALLS 
#define LV_2_WALLS_SIZE LV_CROSS_WALLS_SIZE


// [boss level] Level 3 - shown as 4
//

// Level 4 - shown as 5
#define LV_4_OBJECTS LV_HORIZ_WALLS_OBJECTS
#define LV_4_OBJECTS_SIZE LV_HORIZ_WALLS_OBJECTS_SIZE
#define LV_4_SHURIKENS LV_HORIZ_WALLS_SHURIKENS
#define LV_4_SHURIKENS_SIZE LV_HORIZ_WALLS_SHURIKENS_SIZE
#define LV_4_WALLS LV_HORIZ_WALLS_WALLS 
#define LV_4_WALLS_SIZE LV_HORIZ_WALLS_WALLS_SIZE


// Level 5 - shown as 6
#define LV_5_OBJECTS LV_H_BARRIERS_OBJECTS
#define LV_5_OBJECTS_SIZE LV_H_BARRIERS_OBJECTS_SIZE
#define LV_5_SHURIKENS LV_H_BARRIERS_SHURIKENS
#define LV_5_SHURIKENS_SIZE LV_H_BARRIERS_SHURIKENS_SIZE
#define LV_5_WALLS LV_H_BARRIERS_WALLS 
#define LV_5_WALLS_SIZE LV_H_BARRIERS_WALLS_SIZE


// Level 6 - shown as 7
#define LV_6_OBJECTS LV_RAIN_OBJECTS
#define LV_6_OBJECTS_SIZE LV_RAIN_OBJECTS_SIZE
#define LV_6_SHURIKENS LV_RAIN_SHURIKENS
#define LV_6_SHURIKENS_SIZE LV_RAIN_SHURIKENS_SIZE
#define LV_6_WALLS LV_RAIN_WALLS 
#define LV_6_WALLS_SIZE LV_RAIN_WALLS_SIZE


// [boss level] Level 7 - shown as 8
//

// Level 8 - shown as 9
#define LV_8_OBJECTS LV_VERT_WALLS_OBJECTS
#define LV_8_OBJECTS_SIZE LV_VERT_WALLS_OBJECTS_SIZE
#define LV_8_SHURIKENS LV_VERT_WALLS_SHURIKENS
#define LV_8_SHURIKENS_SIZE LV_VERT_WALLS_SHURIKENS_SIZE
#define LV_8_WALLS LV_VERT_WALLS_WALLS 
#define LV_8_WALLS_SIZE LV_VERT_WALLS_WALLS_SIZE


// Level 9 - shown as 10
#define LV_9_OBJECTS LV_SQUARES_OBJECTS
#define LV_9_OBJECTS_SIZE LV_SQUARES_OBJECTS_SIZE
#define LV_9_SHURIKENS LV_SQUARES_SHURIKENS
#define LV_9_SHURIKENS_SIZE LV_SQUARES_SHURIKENS_SIZE
#define LV_9_WALLS LV_SQUARES_WALLS 
#define LV_9_WALLS_SIZE LV_SQUARES_WALLS_SIZE

// Level 10 - shown as 11
#define LV_10_OBJECTS LV_MANY_OBJECTS
#define LV_10_OBJECTS_SIZE LV_MANY_OBJECTS_SIZE
#define LV_10_SHURIKENS LV_MANY_SHURIKENS
#define LV_10_SHURIKENS_SIZE LV_MANY_SHURIKENS_SIZE
#define LV_10_WALLS LV_MANY_WALLS 
#define LV_10_WALLS_SIZE LV_MANY_WALLS_SIZE


// [boss level] Level 11 - shown as 12 
//

// ----------------------------------------------------------
// Objects: static walls and collectable items
const uint8_t objects_map[] =
{

	LV_0_OBJECTS,
	
	LV_1_OBJECTS,
    
	LV_2_OBJECTS,
	
	LV_4_OBJECTS,
    
    LV_5_OBJECTS,
    
    LV_6_OBJECTS,
	
    LV_8_OBJECTS,
    
    LV_9_OBJECTS,
    
    LV_10_OBJECTS,
	
	LV_CHALLENGE_OBJECTS
};


const uint16_t objects_index[] = 
{
	0, // level 0
	LV_0_OBJECTS_SIZE, // level 1
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE, // level 2
    0,    // level 3  (challenge)
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE, // level 4
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_4_OBJECTS_SIZE, // level 5
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE, // level 6
    0,    // level 7  (challenge)
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE+LV_6_OBJECTS_SIZE, // level 8
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE+LV_6_OBJECTS_SIZE+LV_8_OBJECTS_SIZE, // level 9
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE+LV_6_OBJECTS_SIZE+LV_8_OBJECTS_SIZE+LV_9_OBJECTS_SIZE,
	0,
	LV_0_OBJECTS_SIZE+LV_1_OBJECTS_SIZE+LV_2_OBJECTS_SIZE+LV_4_OBJECTS_SIZE+LV_5_OBJECTS_SIZE+LV_6_OBJECTS_SIZE+LV_8_OBJECTS_SIZE+LV_9_OBJECTS_SIZE+LV_10_OBJECTS_SIZE,
    // 0, // level 11 (challenge)
};


// ----------------------------------------------------------
// Shurikens: horizontal, vertical and mini-shurikens
const uint8_t shurikens_map[] =
{

	LV_0_SHURIKENS,
	
	// level=1
   	LV_1_SHURIKENS,

    // level=2
   	LV_2_SHURIKENS,
        
    // level=3
	LV_4_SHURIKENS,
    
    //
    LV_5_SHURIKENS,
  
    //
    LV_6_SHURIKENS,
	
	//
	LV_8_SHURIKENS,
    
    //
    LV_9_SHURIKENS,
    
    //
    LV_10_SHURIKENS,
    
};

// cross, squares, many
const uint8_t shurikens_index[] = 
{
	0,
	LV_0_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE,
    LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE, // challenge (same as CROSS level)
    
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE+LV_8_SHURIKENS_SIZE, // challenge (same as squares)
    
    LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE+LV_8_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE+LV_8_SHURIKENS_SIZE+LV_9_SHURIKENS_SIZE,
	LV_0_SHURIKENS_SIZE+LV_1_SHURIKENS_SIZE+LV_2_SHURIKENS_SIZE+LV_4_SHURIKENS_SIZE+LV_5_SHURIKENS_SIZE+LV_6_SHURIKENS_SIZE+LV_8_SHURIKENS_SIZE+LV_9_SHURIKENS_SIZE, // This is CORRECT - challenge
    // 1+2*12+1+1,
    // 1+2*12+1+1+ 1+2*2+1+1+4*1,
    // 1+2*12+1+1+ 1+2*2+1+1+4*1+ 1+2*2+ 1+4*2+ 1,    
    // TODO: ....
};



// ----------------------------------------------------------
// Walls: dynamic walls
const uint8_t walls_map[] =
{
	LV_0_WALLS,
	LV_1_WALLS,
	LV_2_WALLS,
	LV_4_WALLS,
    LV_5_WALLS,
    LV_6_WALLS,
	LV_8_WALLS,
    LV_9_WALLS,
    LV_10_WALLS,
	LV_CHALLENGE_WALLS,
};

const uint8_t walls_index[] =
{
	0,
	LV_0_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE+LV_8_WALLS_SIZE+LV_9_WALLS_SIZE+LV_10_WALLS_SIZE, // challenge walls
	
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE+LV_8_WALLS_SIZE+LV_9_WALLS_SIZE+LV_10_WALLS_SIZE, // challenge walls
	
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE+LV_8_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE+LV_8_WALLS_SIZE+LV_9_WALLS_SIZE,
	LV_0_WALLS_SIZE+LV_1_WALLS_SIZE+LV_2_WALLS_SIZE+LV_4_WALLS_SIZE+LV_5_WALLS_SIZE+LV_6_WALLS_SIZE+LV_8_WALLS_SIZE+LV_9_WALLS_SIZE+LV_10_WALLS_SIZE, // challenge walls

    // 0,
    // 1,
    // 1+1+2*8,
};

