// DODGE THE RAIN:
// Initial version generated by QWEN 3.8 27B Q2


#include "cross_lib.h"

/* ──────────── Constants ──────────── */
#define MAX_DROPS   XSize
#define MAX_LIVES   3
#define SPAWN_EVERY 3      /* base frames between spawns */
#define SPEED_RAMP  40      /* frames per difficulty level */


#define DROP_TILE   _TILE_5
#define PLAYER_TILE _TILE_0


/* ──────────── Types ──────────────── */

typedef struct {
    uint8_t active;   /* 1 = in play, 0 = empty slot */
    uint8_t x;        /* column (0..XSize) */
    uint8_t y;        /* row    (0..YSize) */
} Drop;

/* ──────────── Game state ───────────── */

enum GameState { STATE_TITLE, STATE_PLAYING, STATE_GAMEOVER };

static Drop   drops[MAX_DROPS];
static uint8_t player_x;

#define PLAYER_Y ((YSize)-2)

static uint16_t score;          /* frames survived */
static uint8_t lives;
static uint8_t spawn_timer;

/* ──────────── Helpers ─────────────── */

void reset_drops(void) {
    uint8_t i;
    for (i = 0; i < MAX_DROPS; i++) {
        drops[i].active = 0;
    }
}

uint8_t find_empty_slot(void) {
    uint8_t i;
    for (i = 0; i < MAX_DROPS; i++) {
        if (!drops[i].active) return i;
    }
    return MAX_DROPS;   /* all full */
}

void spawn_drop(void) {
    uint8_t slot;

    slot = find_empty_slot();
    if (slot == MAX_DROPS) return;  /* no room */

    drops[slot].active = 1;
    drops[slot].x      = XSize/5 + _XL_RAND()%(XSize-XSize/5-XSize/5);
    drops[slot].y      = 1;
}

void draw_score(void) {
    _XL_SET_TEXT_COLOR(_XL_WHITE);
    _XL_PRINTD(XSize-6, 0, 5, score);
}


void update_drops(void) {
    uint8_t i;

    for (i = 0; i < MAX_DROPS; i++) 
    {
        if (!drops[i].active) continue;

        _XL_DELETE(drops[i].x, drops[i].y);
        /* Move drop down */
        ++drops[i].y;

        /* Remove if it fell off the bottom */
        if (drops[i].y > YSize-2) {
            drops[i].active = 0;
            ++score;
            draw_score();
        }
    }
}

uint8_t check_collision(void) {
    uint8_t i;
    for (i = 0; i < MAX_DROPS; i++) {
        if (!drops[i].active) continue;
        /* Simple: same tile position */
        if (drops[i].x == player_x && drops[i].y == PLAYER_Y) {
            return 1;
        }
    }
    return 0;
}

/* ──────────── Rendering ────────────── */

void draw_lives(void) {
    uint8_t i;
    for (i = 0; i < MAX_LIVES; i++) {
        if (i < lives) {
            _XL_DRAW((uint8_t)(i + 1), 0, PLAYER_TILE, _XL_CYAN);      /* heart tile */
        } else {
            _XL_DELETE((uint8_t)(i + 1), 0);                /* empty slot */
        }
    }
}


/* ──────────── Title screen ─────────── */

void show_title(void) {
    _XL_CLEAR_SCREEN();
    _XL_SET_TEXT_COLOR(_XL_CYAN);
    _XL_PRINT(XSize/2-3, 3, "DODGE");
    _XL_SET_TEXT_COLOR(_XL_WHITE);
    _XL_PRINT(XSize/2-7, 7, "AVOID THE DROPS");
    _XL_PRINT(XSize/2-7, 9,         "GOOD LUCK");
    _XL_WAIT_FOR_INPUT();
}

/* ──────────── Game over screen ─────── */

void show_gameover(void) {
    uint8_t i;
    _XL_CLEAR_SCREEN();
    for (i = 0; i < MAX_DROPS; i++) drops[i].active = 0;

    _XL_SET_TEXT_COLOR(_XL_RED);
    _XL_PRINT(4, 3, "GAME OVER");
    _XL_SET_TEXT_COLOR(_XL_WHITE);
    _XL_PRINTD(4, 6, 5, score);
    // _XL_PRINT(10, 6, "FRAMES");
    _XL_WAIT_FOR_INPUT();
}

/* ──────────── Main loop ────────────── */

int main(void) {
    uint8_t input;
    uint8_t hit;
    uint16_t slowdown;
    uint8_t counter;
    uint8_t difficulty;
    
    _XL_INIT_GRAPHICS();
    _XL_INIT_INPUT();
    _XL_INIT_SOUND();


    while(1)
    {
        /* ── Title ── */
        show_title();

        /* ── Reset game state ── */
        reset_drops();
        player_x  = (uint8_t)(XSize / 2);
        score     = 0;
        lives     = MAX_LIVES;
        spawn_timer = 0;

        counter = 254;
        draw_lives();
        difficulty = 1;
        
        _XL_CLEAR_SCREEN();
        _XL_DRAW(player_x, PLAYER_Y, PLAYER_TILE, _XL_CYAN);
        
        slowdown = _XL_SLOW_DOWN_FACTOR;

        draw_score();

        /* ── Playing loop ── */
        while (lives > 0) {

            /* Draw HUD */

            /* Spawn logic: interval shrinks as difficulty rises */
            spawn_timer++;
            {
                // uint8_t interval = (uint8_t)(SPAWN_EVERY - (difficulty > 6 ? 6 : difficulty));
                // if (interval < 3) interval = 3;   /* don't go below 3 */
                if (spawn_timer >= SPAWN_EVERY) {
                    spawn_drop();
                    spawn_timer = 0;
                }
            }

            /* Update drops */
            update_drops();

            /* Draw drops */
            {
                uint8_t i;
                for (i = 0; i < MAX_DROPS; i++) {
                    if (!drops[i].active) continue;
                    _XL_DRAW(drops[i].x, drops[i].y, DROP_TILE, _XL_RED);
                }
            }

            ++counter;
            if(!counter)
            {
                ++difficulty;
                slowdown = _XL_SLOW_DOWN_FACTOR/(2+(difficulty>>3));
                counter = 224;
            }
            /* Timing */
            _XL_SLOW_DOWN(slowdown);

            /* Poll input and move player */
            input = _XL_INPUT();

            if (_XL_LEFT(input) && player_x >XSize/5)  
            { 
                _XL_DELETE(player_x, PLAYER_Y);
                
                player_x--; 
                       /* Draw player */
                _XL_DRAW(player_x, PLAYER_Y, PLAYER_TILE, _XL_CYAN); 
            }
            if (_XL_RIGHT(input) && player_x < XSize-1-XSize/5) 
            { 
                _XL_DELETE(player_x, PLAYER_Y);

                player_x++; 
                /* Draw player */
                _XL_DRAW(player_x, PLAYER_Y, PLAYER_TILE, _XL_CYAN);
            }
            // if (_XL_UP(input))    { player_y--; }
            // if (_XL_DOWN(input))  { player_y++; }

            /* Clamp */

            // if (player_y > YSize) player_y = YSize;

            /* Collision check */
            hit = check_collision();
            if (hit) {
                lives--;
                /* Brief pause so the hit is visible */
                _XL_SLEEP(1);
                /* Clear all drops on hit for fairness */
                reset_drops();
                _XL_CLEAR_SCREEN();
                _XL_DRAW(player_x, PLAYER_Y, PLAYER_TILE, _XL_CYAN);
                draw_lives();
                _XL_SLEEP(1);
                if(lives)
                {
                    _XL_WAIT_FOR_INPUT();
                }
            }

        }

        /* ── Game over ── */
        show_gameover();
    }

    return 0;
}
