;
; File generated by cc65 v 2.16 - Git ce56ba9
;
	.fopt		compiler,"cc65 v 2.16 - Git ce56ba9"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_videomode
	.import		_fast
	.import		_gotoxy
	.import		_cputc
	.import		_textcolor
	.export		__draw_broken_wall
	.export		__draw
	.export		__blink_powerUp_draw
	.export		__blink_gun_draw
	.export		__blink_extra_points_draw
	.export		__blink_extra_life_draw
	.export		__blink_invincibility_draw
	.export		__blink_player_draw
	.export		__delete
	.export		_INIT_IMAGES
	.export		_INIT_GRAPHICS
	.export		_PLAYER_IMAGE
	.export		_GHOST_IMAGE
	.export		_DEAD_GHOST_IMAGE
	.export		_INVINCIBLE_GHOST_IMAGE
	.export		_BOMB_IMAGE
	.export		_POWERUP_IMAGE
	.export		_MISSILE_IMAGE
	.export		_GUN_IMAGE
	.export		_BUBBLE_IMAGE
	.export		_LEFT_ENEMY_MISSILE_IMAGE
	.export		_RIGHT_ENEMY_MISSILE_IMAGE
	.export		_EXTRA_POINTS_IMAGE
	.export		_EXTRA_LIFE_IMAGE
	.export		_INVINCIBILITY_IMAGE
	.export		_powerUp_blink
	.export		_gun_blink
	.export		_extra_points_blink
	.export		_extra_life_blink
	.export		_invincibility_blink
	.export		_player_blink

.segment	"DATA"

_powerUp_blink:
	.byte	$01
_gun_blink:
	.byte	$01
_extra_points_blink:
	.byte	$01
_extra_life_blink:
	.byte	$01
_invincibility_blink:
	.byte	$01
_player_blink:
	.byte	$01

.segment	"BSS"

.segment	"BSS"
_PLAYER_IMAGE:
	.res	2,$00
.segment	"BSS"
_GHOST_IMAGE:
	.res	2,$00
.segment	"BSS"
_DEAD_GHOST_IMAGE:
	.res	2,$00
.segment	"BSS"
_INVINCIBLE_GHOST_IMAGE:
	.res	2,$00
.segment	"BSS"
_BOMB_IMAGE:
	.res	2,$00
.segment	"BSS"
_POWERUP_IMAGE:
	.res	2,$00
.segment	"BSS"
_MISSILE_IMAGE:
	.res	2,$00
.segment	"BSS"
_GUN_IMAGE:
	.res	2,$00
.segment	"BSS"
_BUBBLE_IMAGE:
	.res	2,$00
.segment	"BSS"
_LEFT_ENEMY_MISSILE_IMAGE:
	.res	2,$00
.segment	"BSS"
_RIGHT_ENEMY_MISSILE_IMAGE:
	.res	2,$00
.segment	"BSS"
_EXTRA_POINTS_IMAGE:
	.res	2,$00
.segment	"BSS"
_EXTRA_LIFE_IMAGE:
	.res	2,$00
.segment	"BSS"
_INVINCIBILITY_IMAGE:
	.res	2,$00

; ---------------------------------------------------------------
; void __near__ _draw_broken_wall (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__draw_broken_wall: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	lda     #$01
	jsr     _textcolor
	lda     #$D8
	jsr     _cputc
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ _draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_powerUp_draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_powerUp_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	lda     _powerUp_blink
	beq     L006B
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	lda     #$00
	jmp     L00D5
L006B:	lda     #$20
	jsr     _cputc
	lda     #$01
L00D5:	sta     _powerUp_blink
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_gun_draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_gun_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	lda     _gun_blink
	beq     L007E
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	lda     #$00
	jmp     L00D6
L007E:	lda     #$20
	jsr     _cputc
	lda     #$01
L00D6:	sta     _gun_blink
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_extra_points_draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_extra_points_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	lda     _extra_points_blink
	beq     L0091
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	lda     #$00
	jmp     L00D7
L0091:	lda     #$20
	jsr     _cputc
	lda     #$01
L00D7:	sta     _extra_points_blink
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_extra_life_draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_extra_life_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	lda     _extra_life_blink
	beq     L00A4
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	lda     #$00
	jmp     L00D8
L00A4:	lda     #$20
	jsr     _cputc
	lda     #$01
L00D8:	sta     _extra_life_blink
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_invincibility_draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_invincibility_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	lda     _invincibility_blink
	beq     L00B7
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	lda     #$00
	jmp     L00D9
L00B7:	lda     #$20
	jsr     _cputc
	lda     #$01
L00D9:	sta     _invincibility_blink
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_player_draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_player_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	jsr     _textcolor
	lda     _player_blink
	beq     L00CA
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	lda     #$00
	jmp     L00DA
L00CA:	lda     #$20
	jsr     _cputc
	lda     #$01
L00DA:	sta     _player_blink
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ _delete (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__delete: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	adc     #$03
	jsr     _gotoxy
	lda     #$20
	jsr     _cputc
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ INIT_IMAGES (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_INIT_IMAGES: near

.segment	"CODE"

	lda     #$03
	sta     _PLAYER_IMAGE+1
	lda     #$01
	sta     _INVINCIBLE_GHOST_IMAGE+1
	lda     #$07
	sta     _POWERUP_IMAGE+1
	lda     #$09
	sta     _GUN_IMAGE+1
	lda     #$02
	sta     _BOMB_IMAGE+1
	sta     _DEAD_GHOST_IMAGE+1
	lda     #$07
	sta     _EXTRA_POINTS_IMAGE+1
	sta     _EXTRA_LIFE_IMAGE+1
	sta     _INVINCIBILITY_IMAGE+1
	lda     #$4F
	sta     _GHOST_IMAGE
	lda     #$2B
	sta     _INVINCIBLE_GHOST_IMAGE
	lda     #$D8
	sta     _BOMB_IMAGE
	lda     #$2A
	sta     _PLAYER_IMAGE
	lda     #$D3
	sta     _POWERUP_IMAGE
	lda     #$21
	sta     _GUN_IMAGE
	lda     #$2E
	sta     _MISSILE_IMAGE
	lda     _BOMB_IMAGE
	sta     _DEAD_GHOST_IMAGE
	lda     #$01
	sta     _GHOST_IMAGE+1
	sta     _MISSILE_IMAGE+1
	lda     #$3E
	sta     _LEFT_ENEMY_MISSILE_IMAGE
	lda     #$01
	sta     _LEFT_ENEMY_MISSILE_IMAGE+1
	lda     #$3C
	sta     _RIGHT_ENEMY_MISSILE_IMAGE
	lda     #$01
	sta     _RIGHT_ENEMY_MISSILE_IMAGE+1
	lda     #$5E
	sta     _BUBBLE_IMAGE
	lda     #$01
	sta     _BUBBLE_IMAGE+1
	lda     #$24
	sta     _EXTRA_POINTS_IMAGE
	lda     _PLAYER_IMAGE
	sta     _EXTRA_LIFE_IMAGE
	lda     #$D6
	sta     _INVINCIBILITY_IMAGE
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ INIT_GRAPHICS (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_INIT_GRAPHICS: near

.segment	"CODE"

	jsr     _fast
	ldx     #$00
	lda     #$50
	jmp     _videomode

.endproc

