# ------------------------------------------------------------------------------------------
# Z88DK
#

################################################################################

# missing: abc800, xo7, c7420, rex
# missing 8080: m100
z88dk_targets_sccz80:
	make $(Z88DK_MAKE_OPTS) z88dk_targets_a-k 
	make $(Z88DK_MAKE_OPTS) z88dk_targets_l-p 
	make $(Z88DK_MAKE_OPTS) z88dk_targets_q-z

z88dk_targets:
	make $(Z88DK_MAKE_OPTS) z88dk_targets_sccz80
	make $(Z88DK_MAKE_OPTS) z88dk_targets_zsdcc 


##################################################################

include makefiles.chase/makefiles_z88dk/Makefile_z88dk_a-k

include makefiles.chase/makefiles_z88dk/Makefile_z88dk_l-p

include makefiles.chase/makefiles_z88dk/Makefile_z88dk_q-z

include makefiles.chase/makefiles_z88dk/Makefile_z88dk_zsdcc

# ----------------------------------------------------------------

