;
; File generated by cc65 v 2.17 - Git d002f6e
;
	.fopt		compiler,"cc65 v 2.17 - Git d002f6e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_WAIT_PRESS
	.import		_joy_read

; ---------------------------------------------------------------
; void __near__ WAIT_PRESS (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_WAIT_PRESS: near

.segment	"CODE"

L0006:	lda     #$00
	jsr     _joy_read
	and     #$80
	bne     L0006
L0012:	jsr     _joy_read
	and     #$80
	beq     L0012
	rts

.endproc

