#ifndef _IMAGES_H
#define _IMAGES_H

#include "cross_lib.h"


    Image THREE_WINDOW_WALL_1_IMAGE;
    Image PLANE_BACK_IMAGE;
    Image PLANE_FRONT_IMAGE;
    // Image CONTROL_TOWER_IMAGE;
    
    Image ANIMATED_PLANE_BACK_IMAGE;
    Image ANIMATED_PLANE_CENTER_IMAGE;
    Image ANIMATED_PLANE_FRONT_IMAGE;
    
    Image SMALL_TWO_WINDOW_WALL_1_IMAGE;
    Image WALL_1_IMAGE;	

    Image FIRE_POWER_IMAGE;	
    Image TWO_WINDOW_WALL_1_IMAGE;		

    Image HORIZONTAL_BRICK_IMAGE;
    Image VERTICAL_BRICK_IMAGE;	

    Image BOMB_IMAGE;
    Image ANIMATED_BOMB_UP_IMAGE;
    Image ANIMATED_BOMB_DOWN_IMAGE;

    Image ROAD_IMAGE;	

    Image THREE_WINDOW_WALL_2_IMAGE;

    Image TWO_WINDOW_WALL_2_IMAGE;
    Image SMALL_TWO_WINDOW_WALL_2_IMAGE;

    Image WALL_2_IMAGE;

    Image SCORE_TEXT_LEFT_IMAGE;
    Image SCORE_TEXT_RIGHT_IMAGE;
    
    Image HI_TEXT_IMAGE;
    Image LV_TEXT_IMAGE;
    
    Image EXPLOSION_IMAGE;

#endif // _IMAGES_H

