
FULL_FILES ?= \
	$(BASIC_CROSS_LIB_FILES) \
    $(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(SOURCE_PATH)/main.c 

GAME_NAME := trex

PARENT_DIR = examples

include ./$(PARENT_DIR)/$(GAME_NAME)/config/project_config.mk

include ./Makefile_common
