#

COCO_COLOR_GFX_GAME_OPTS ?= 

CREATIVISION_GAME_OPTS ?=  

GAMATE_GAME_OPTS ?=

C128_Z80_80COL_GAME_OPTS ?=  -DFEWER_SHURIKENS

ZX81_NO_GFX_GAME_OPTS ?=

ZX81_GFX_GAME_OPTS ?=  -DFEWER_SHURIKENS

APPLE2_GAME_OPTS ?= 

COMX_GAME_OPTS ?= 

PECOM_GAME_OPTS ?= 

TMC600_GAME_OPTS ?= 

MICRO_GAME_OPTS ?= 

CAMPUTERS_LYNX_GAME_OPTS ?= -DFEWER_SHURIKENS

__VIC20_EXP_3K_GAME_OPTS ?= 

__VIC20_UNEXPANDED_GAME_OPTS ?= 

STDIO_GAME_OPTS ?= 