
FULL_FILES ?= \
	$(BASIC_CROSS_LIB_FILES) \
    $(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(SOURCE_PATH)/main.c 

GAME_NAME := helloworld

PARENT_DIR = examples

include ./Makefile_common
