* 6809 assembly program generated by cmoc 0.1.56


	SECTION	code


_udgs	EXPORT


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ0ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Globals with static initializers
_udgs	EQU	*		udgs: uint8_t[]



	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000

; invincibility
    FCB 66 
    FCB 66 
    FCB 90 
    FCB 126 
    FCB 60 
    FCB 60 
    FCB 60 
    FCB 24


; left missile
    FCB 128 
    FCB 0 
    FCB 128 
    FCB 192 
    FCB 224 
    FCB 160 
    FCB 160 
    FCB 0


; bullet
    FCB 32 
    FCB 17 
    FCB 63 
    FCB 110 
    FCB 255 
    FCB 191 
    FCB 160 
    FCB 27


; dollar $
	FCB %00000000
	FCB %00001000
	FCB %00111110
	FCB %00101000
	FCB %00111110
	FCB %00001010
	FCB %00111110
	FCB %00001000

; power-up F
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 224 
    FCB 240 
    FCB 0 
    FCB 0


; vertical brick
    FCB 15 
    FCB 127 
    FCB 255 
    FCB 230 
    FCB 255 
    FCB 25 
    FCB 54 
    FCB 192


; skull
    FCB 0 
    FCB 7 
    FCB 15 
    FCB 14 
    FCB 15 
    FCB 3 
    FCB 6 
    FCB 3


; ghost
    FCB 64 
    FCB 224 
    FCB 224 
    FCB 252 
    FCB 254 
    FCB 254 
    FCB 254 
    FCB 254


; bomb
    FCB 1 
    FCB 3 
    FCB 7 
    FCB 13 
    FCB 15 
    FCB 2 
    FCB 5 
    FCB 10


; player down
    FCB 1 
    FCB 3 
    FCB 3 
    FCB 31 
    FCB 63 
    FCB 63 
    FCB 63 
    FCB 63


; horizontal brick
    FCB 0 
    FCB 224 
    FCB 240 
    FCB 112 
    FCB 240 
    FCB 128 
    FCB 192 
    FCB 48


; power-up S
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 192 
    FCB 129 
    FCB 255 
    FCB 255 
    FCB 255


	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00111110
	FCB %00000000
	FCB %00000000
	FCB %00000000

; right missile
    FCB 2 
    FCB 9 
    FCB 11 
    FCB 14 
    FCB 15 
    FCB 7 
    FCB 2 
    FCB 4


; rocket
    FCB 8 
    FCB 18 
    FCB 250 
    FCB 238 
    FCB 254 
    FCB 252 
    FCB 8 
    FCB 4


	FCB %00000000 ; 
	FCB %00111100 ;  ####
	FCB %01000110 ; #   ## 
	FCB %01001010 ; #  # # 
	FCB %01010010 ; # #  # 
	FCB %01100010 ; ##   #
	FCB %00111100 ;  ####
	FCB %00000000

    FCB 0 
    FCB 0 
    FCB 0 
    FCB 1 
    FCB 3 
    FCB 3 
    FCB 3 
    FCB 3

    FCB 16 
    FCB 56 
    FCB 56 
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 255

    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 128 
    FCB 128 
    FCB 128 
    FCB 128

    FCB 4 
    FCB 14 
    FCB 14 
    FCB 127 
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 255

    FCB 0 
    FCB 0 
    FCB 0 
    FCB 192 
    FCB 224 
    FCB 224 
    FCB 224 
    FCB 224

    FCB 240 
    FCB 254 
    FCB 255 
    FCB 103 
    FCB 255 
    FCB 156 
    FCB 102 
    FCB 12


	FCB %00000000
	FCB %01111110
	FCB %00000010
	FCB %00000100
	FCB %00001000
	FCB %00010000
	FCB %00010000
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111100
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111110
	FCB %00000010
	FCB %00111100
	FCB %00000000

; dead ghost
    FCB 128 
    FCB 192 
    FCB 224 
    FCB 176 
    FCB 240 
    FCB 64 
    FCB 160 
    FCB 80


; power-up H
    FCB 24 
    FCB 60 
    FCB 126 
    FCB 219 
    FCB 255 
    FCB 90 
    FCB 129 
    FCB 66


; player up
    FCB 0 
    FCB 128 
    FCB 128 
    FCB 240 
    FCB 248 
    FCB 248 
    FCB 248 
    FCB 248


; player right
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 7 
    FCB 15 
    FCB 15 
    FCB 15 
    FCB 15


; player left
    FCB 64 
    FCB 224 
    FCB 224 
    FCB 252 
    FCB 254 
    FCB 254 
    FCB 254 
    FCB 254


; gun
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 50 
    FCB 0






	ENDSECTION




	SECTION	bss


* Uninitialized globals
bss_start	EQU	*
bss_end	EQU	*


	ENDSECTION




	SECTION	code




	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END





