#!/bin/sh
# Assemble bootloaders and generate C code
#

BOOTASM="$1.asm"
BOOTBIN1="$1.10.bin"
BOOTBIN2="$1.20.bin"
BOOTH="$1.h"

if [ ! -f "$BOOTASM" ]; then
    echo "ERROR, specify bootloader file name"
    exit 1
fi

# Assemble at two different addresses:
mads $BOOTASM -d:BASE_ADDRESS='$1000' -l -o:$BOOTBIN1
mads $BOOTASM -d:BASE_ADDRESS='$2000' -l -o:$BOOTBIN2

# Generate header file
cat > $BOOTH <<EOF
#pragma once

/*
 * Autogenerated file from $BOOTASM
 * Do not edit.
 */

static unsigned char $1_bin[384] = {
$(od $BOOTBIN1 -An -tu1 -v | sed -e 's/\([0-9][0-9]*\)/\1,/g')
};

static unsigned $1_reloc[] = {
$(cmp -l $BOOTBIN1 $BOOTBIN2  |
  sed -e 's/^\( *[0-9][0-9]*\).*$/\1,/' |
  sed -e ':a;N;s/\n//;ta' |
  sed -e 's/,$//' )
};

EOF

rm -f $BOOTBIN1 $BOOTBIN2
