#ifndef _INIT_IMAGES_H
#define _INIT_IMAGES_H

#define _PLAYER_DOWN_TILE  _TILE_0
#define _PLAYER_UP_TILE    _TILE_1
#define _PLAYER_RIGHT_TILE _TILE_2
#define _PLAYER_LEFT_TILE  _TILE_3

#define _GHOST_TILE        _TILE_4
#define _SKULL_TILE        _TILE_7
#define _BOSS_TILE         _TILE_6
#define _BULLET_TILE       _TILE_11
#define _FIRE_POWER_TILE   _TILE_9
#define _BOMB_TILE         _TILE_5


#define _PLAYER_COLOR _XL_CYAN
#define _GHOST_COLOR _XL_WHITE
#define _DEAD_GHOST_COLOR _XL_RED
#define _SKULL_COLOR _XL_YELLOW
#define _BOMB_COLOR _XL_RED
#define _MISSILE_COLOR _XL_WHITE
#define _ROCKET_COLOR _XL_WHITE
#define _CALM_DOWN_COLOR _XL_GREEN
#define _FIRE_CHARGE_COLOR _XL_GREEN
#define _FREEZE_COLOR _XL_CYAN
#define _SUPER_COLOR _XL_RED
#define _FIRE_POWER_COLOR _XL_YELLOW
#define _BULLET_COLOR _XL_WHITE
#define _BRICK_COLOR _XL_GREEN
#define _BROKEN_BRICK_COLOR _XL_YELLOW
#define _EXTRA_POINTS_COLOR _XL_YELLOW
#define _EXTRA_LIFE_COLOR _XL_WHITE
#define _INVINCIBILITY_COLOR _XL_YELLOW
#define _CONFUSE_COLOR _XL_RED
#define _SUICIDE_COLOR _XL_YELLOW


void INIT_IMAGES(void);




#endif // _INIT_IMAGES_H

