#ifndef _INIT_IMAGES_H
#define _INIT_IMAGES_H

#if !defined(NO_COLOR)
    #define _PLANE_COLOR COLOR_CYAN
    #define _SMALL_TWO_WINDOW_WALL_1_COLOR COLOR_WHITE
    #define _TWO_WINDOW_WALL_1_COLOR COLOR_YELLOW
    #define _WALL_1_COLOR COLOR_RED
    #define _BOMB_COLOR COLOR_WHITE
    #define _ROAD_COLOR COLOR_CYAN
    #define _BRICK_COLOR COLOR_GREEN
    #define _WALL_2_COLOR COLOR_YELLOW
    #define _THREE_WINDOW_WALL_1_COLOR COLOR_WHITE
    #define _THREE_WINDOW_WALL_2_COLOR COLOR_WHITE
    #define _TWO_WINDOW_WALL_2_COLOR COLOR_RED
    #define _SMALL_TWO_WINDOW_WALL_2_COLOR COLOR_YELLOW
#endif

void INIT_IMAGES(void);


#endif // _INIT_IMAGES_H

