* 6809 assembly program generated by cmoc 0.1.56


	SECTION	code


_udgs	EXPORT


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ0ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Globals with static initializers
_udgs	EQU	*		udgs: uint8_t[]



	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000

; invincibility
    FCB 66 
    FCB 66 
    FCB 90 
    FCB 126 
    FCB 60 
    FCB 60 
    FCB 60 
    FCB 24


; left missile
    FCB $db 
    FCB $92 
    FCB $92 
    FCB $d2 
    FCB $52 
    FCB $52 
    FCB $db 
    FCB $00


; bullet
    FCB 126 
    FCB 102 
    FCB 126 
    FCB 102 
    FCB 126 
    FCB 102 
    FCB 126 
    FCB 102


; dollar $
	FCB %00000000
	FCB %00001000
	FCB %00111110
	FCB %00101000
	FCB %00111110
	FCB %00001010
	FCB %00111110
	FCB %00001000

; power-up F
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 224 
    FCB 240 
    FCB 0 
    FCB 0


; vertical brick
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 66 
    FCB 66 
    FCB 90 
    FCB 126


; skull
    FCB 255 
    FCB 153 
    FCB 255 
    FCB 153 
    FCB 255 
    FCB 153 
    FCB 255 
    FCB 153


; ghost
    FCB 126 
    FCB 90 
    FCB 126 
    FCB 90 
    FCB 126 
    FCB 90 
    FCB 126 
    FCB 90


; bomb
    FCB 126 
    FCB 102 
    FCB 126 
    FCB 102 
    FCB 126 
    FCB 102 
    FCB 126 
    FCB 102


; player down
    FCB 0 
    FCB 0 
    FCB 12 
    FCB 6 
    FCB 7 
    FCB 3 
    FCB 0 
    FCB 0


; horizontal brick
    FCB 60 
    FCB 60 
    FCB 60 
    FCB 24 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0


; power-up S
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 192 
    FCB 129 
    FCB 255 
    FCB 255 
    FCB 255


	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00111110
	FCB %00000000
	FCB %00000000
	FCB %00000000

; right missile
    FCB 255 
    FCB 165 
    FCB 255 
    FCB 165 
    FCB 255 
    FCB 165 
    FCB 255 
    FCB 165


; rocket
    FCB $b3 
    FCB $aa 
    FCB $aa 
    FCB $b3 
    FCB $aa 
    FCB $aa 
    FCB $ab 
    FCB $00


	FCB %00000000 ; 
	FCB %00111100 ;  ####
	FCB %01000110 ; #   ## 
	FCB %01001010 ; #  # # 
	FCB %01010010 ; # #  # 
	FCB %01100010 ; ##   #
	FCB %00111100 ;  ####
	FCB %00000000

    FCB 255 
    FCB 255 
    FCB 0 
    FCB 48 
    FCB 48 
    FCB 0 
    FCB 255 
    FCB 255

    FCB 255 
    FCB 255 
    FCB 0 
    FCB 48 
    FCB 48 
    FCB 0 
    FCB 255 
    FCB 255

    FCB 255 
    FCB 255 
    FCB 0 
    FCB 48 
    FCB 48 
    FCB 0 
    FCB 255 
    FCB 255

    FCB 255 
    FCB 255 
    FCB 0 
    FCB 48 
    FCB 48 
    FCB 0 
    FCB 255 
    FCB 255

    FCB 255 
    FCB 255 
    FCB 0 
    FCB 48 
    FCB 48 
    FCB 0 
    FCB 255 
    FCB 255

    FCB 255 
    FCB 255 
    FCB 0 
    FCB 48 
    FCB 48 
    FCB 0 
    FCB 255 
    FCB 255


	FCB %00000000
	FCB %01111110
	FCB %00000010
	FCB %00000100
	FCB %00001000
	FCB %00010000
	FCB %00010000
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111100
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111110
	FCB %00000010
	FCB %00111100
	FCB %00000000

; dead ghost
    FCB $54 
    FCB $54 
    FCB $54 
    FCB $74 
    FCB $54 
    FCB $54 
    FCB $54 
    FCB $00


; power-up H
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 170 
    FCB 255 
    FCB 255


; player up
    FCB 12 
    FCB 6 
    FCB 195 
    FCB 97 
    FCB 127 
    FCB 63 
    FCB 1 
    FCB 3


; player right
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 128 
    FCB 254 
    FCB 255 
    FCB 128 
    FCB 0


; player left
    FCB 192 
    FCB 96 
    FCB 48 
    FCB 24 
    FCB 255 
    FCB 255 
    FCB 24 
    FCB 48


; gun
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 37 
    FCB 50 
    FCB 0






	ENDSECTION




	SECTION	bss


* Uninitialized globals
bss_start	EQU	*
bss_end	EQU	*


	ENDSECTION




	SECTION	code




	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END





