#
#  Makefile for building getmemo7, getrom and wav2k7.
#
#  Available options:
#
#     Environment variables:
#        FRENCH=1          (by default) create a french build (djgpp only).
#        ENGLISH=1         create an english build (djgpp only).
#
#     Targets: 
#        all:              build executables files
#        clean:            remove objects and executable files.
#

ifdef DJDIR

include makefile.dj

else

include makefile.lnx

endif
