* 6809 assembly program generated by cmoc 0.1.56


	SECTION	code


_udgs	EXPORT


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ0ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Globals with static initializers
_udgs	EQU	*		udgs: uint8_t[]



	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000

; invincibility
    FCB 170 
    FCB 0 
    FCB 170 
    FCB 0 
    FCB 170 
    FCB 0 
    FCB 170 
    FCB 0


; left missile
    FCB $db 
    FCB $92 
    FCB $92 
    FCB $d2 
    FCB $52 
    FCB $52 
    FCB $db 
    FCB $00


; bullet
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 8 
    FCB 28 
    FCB 116 
    FCB 198


; dollar $
	FCB %00000000
	FCB %00001000
	FCB %00111110
	FCB %00101000
	FCB %00111110
	FCB %00001010
	FCB %00111110
	FCB %00001000

; power-up F
    FCB 16 
    FCB 56 
    FCB 46 
    FCB 99 
    FCB 198 
    FCB 116 
    FCB 28 
    FCB 8


; vertical brick
    FCB 90 
    FCB 126 
    FCB 90 
    FCB 126 
    FCB 90 
    FCB 126 
    FCB 90 
    FCB 126


; skull
    FCB 170 
    FCB 255 
    FCB 170 
    FCB 255 
    FCB 170 
    FCB 255 
    FCB 170 
    FCB 255


; ghost
    FCB 60 
    FCB 126 
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 255 
    FCB 126 
    FCB 60


; bomb
    FCB 48 
    FCB 8 
    FCB 126 
    FCB 255 
    FCB 253 
    FCB 253 
    FCB 255 
    FCB 126


; player down
    FCB 60 
    FCB 126 
    FCB 255 
    FCB 153 
    FCB 153 
    FCB 255 
    FCB 126 
    FCB 60


; horizontal brick
    FCB 0 
    FCB 255 
    FCB 170 
    FCB 255 
    FCB 255 
    FCB 170 
    FCB 255 
    FCB 0


; power-up S
    FCB 60 
    FCB 126 
    FCB 231 
    FCB 195 
    FCB 195 
    FCB 231 
    FCB 126 
    FCB 60


	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00111110
	FCB %00000000
	FCB %00000000
	FCB %00000000

; right missile
    FCB 99 
    FCB 46 
    FCB 56 
    FCB 16 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0


; rocket
    FCB $b3 
    FCB $aa 
    FCB $aa 
    FCB $b3 
    FCB $aa 
    FCB $aa 
    FCB $ab 
    FCB $00


	FCB %00000000 ; 
	FCB %00111100 ;  ####
	FCB %01000110 ; #   ## 
	FCB %01001010 ; #  # # 
	FCB %01010010 ; # #  # 
	FCB %01100010 ; ##   #
	FCB %00111100 ;  ####
	FCB %00000000

    FCB 16 
    FCB 56 
    FCB 46 
    FCB 99 
    FCB 198 
    FCB 116 
    FCB 28 
    FCB 8

    FCB 153 
    FCB 255 
    FCB 126 
    FCB 60 
    FCB 60 
    FCB 126 
    FCB 255 
    FCB 255

    FCB 255 
    FCB 255 
    FCB 126 
    FCB 60 
    FCB 60 
    FCB 126 
    FCB 255 
    FCB 153

    FCB 195 
    FCB 103 
    FCB 127 
    FCB 255 
    FCB 255 
    FCB 127 
    FCB 103 
    FCB 195

    FCB 195 
    FCB 230 
    FCB 254 
    FCB 255 
    FCB 255 
    FCB 254 
    FCB 230 
    FCB 195

    FCB 255 
    FCB 255 
    FCB 126 
    FCB 60 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0


	FCB %00000000
	FCB %01111110
	FCB %00000010
	FCB %00000100
	FCB %00001000
	FCB %00010000
	FCB %00010000
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111100
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111110
	FCB %00000010
	FCB %00111100
	FCB %00000000

; dead ghost
    FCB $54 
    FCB $54 
    FCB $54 
    FCB $74 
    FCB $54 
    FCB $54 
    FCB $54 
    FCB $00


; power-up H
    FCB 60 
    FCB 126 
    FCB 231 
    FCB 219 
    FCB 219 
    FCB 231 
    FCB 126 
    FCB 60


; player up
    FCB 60 
    FCB 102 
    FCB 231 
    FCB 255 
    FCB 255 
    FCB 231 
    FCB 102 
    FCB 60


; player right
    FCB 0 
    FCB 1 
    FCB 7 
    FCB 12 
    FCB 6 
    FCB 2 
    FCB 3 
    FCB 1


; player left
    FCB 128 
    FCB 192 
    FCB 64 
    FCB 96 
    FCB 48 
    FCB 224 
    FCB 128 
    FCB 0


; gun
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 100 
    FCB 0






	ENDSECTION




	SECTION	bss


* Uninitialized globals
bss_start	EQU	*
bss_end	EQU	*


	ENDSECTION




	SECTION	code




	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END





