# -----------------------------------------------
# Z88DK

z88dk_alt_targets_a-g: \
    abc80_alt_targets \
    ace_alt_targets \
    aussie_alt_targets \
    c128_z80_alt_targets \
    camputers_alt_targets \
    cpm_z80_alt_targets \
    eg2k_alt_targets \
    fp1100_alt_targets \
    g800_alt_targets

#############################

abc80_alt_targets: \
    abc80_tiny


ace_alt_targets: \
    ace_exp_16k_no_gfx

aussie_alt_targets: \
    aussie_buffered

c128_z80_alt_targets: \
    c128_z80_40col_turn_based

camputers_alt_targets: \
    camputers_lynx_tiny

cpm_z80_alt_targets: \
    cpm_z80_tiny_buffered \
    cpm_z80_buffered \
    cpm_z80_vt52 \
    cpm_z80_vt100

cpc_alt_targets: \
    cpc_no_udg

eg2k_alt_targets: \
    eg2k_no_gfx

fp1100_alt_targets: \
    fp1100_tiny

g800_alt_targets: \
    g800_tiny_turn_based

#############################
# ABC80

abc80_tiny:
	$(Z88DK_PATH)$(MYZ88DK) +abc80 $(SCCZ80_OPTS) -lm -subtype=hex -zorg=49200 $(INCLUDE_OPTS) \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DTINY_GAME \
	-DNO_WAIT \
	-D__ABC80__ -clib=ansi -vn  -lndos -create-app -o abc80t.bin \
	$(TINY_FILES)
	rm abc80t.bin
	mv abc80t.ihx $(BUILD_PATH)/ALT_TINY_abc80.ihx 


#############################
# ACE
ace_exp_16k_no_gfx:
	$(Z88DK_PATH)$(MYZ88DK) +ace $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__ACE__ -DFULL_GAME -DBETWEEN_LEVEL -DEND_SCREEN \
	-DSOUNDS \
	-DCONIO -DNO_INIT_GRAPHICS \
	-clib=ansi -o acengfx.bin -Cz--audio -create-app \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	cp acengfx.wav $(BUILD_PATH)/ALT_FULL_ace_exp_16k_no_gfx.wav
	rm acengfx.wav
	rm acengfx.tap
	rm acengfx.bin


#############################
# AUSSIE
aussie_buffered:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) -laussie  \
	$(INCLUDE_OPTS) \
	-vn \
	-D__AUSSIE__ \
	-DSOUNDS \
	-DFORCE_BIT_BANG \
	-DFORCE_XSIZE=16 \
	-DFORCE_YSIZE=12 \
	-DNO_COLOR \
	-DFULL_GAME \
	-DTURN_BASED \
	-DBUFFERED \
	-DNO_INIT_GRAPHICS \
	-DALT_PRINT \
	-DDEFAULT_CLEAR_SCREEN \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(FULL_FILES) \
	-create-app -o aussieb.bin
	rm aussieb.bin
	mv aussieb.COM $(BUILD_PATH)/ALT_FULL_aussie_buffered.COM


#############################
# C128 Z80
c128_z80_40col_turn_based:
	$(Z88DK_PATH)$(MYZ88DK) +c128 $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-lndos -subtype=disk \
	-D__C128_Z80__ -DFORCE_XSIZE=40 \
	-DFULL_GAME -DEND_SCREEN \
	-DTURN_BASED \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES) \
	-create-app -oa80tb.bin
	$(TOOLS_PATH)/generic/c1541 -format "crosschase,0" d64 ALT_FULL_c128_z80_40col_turn_based.d64
	$(TOOLS_PATH)/generic/c1541 -attach ALT_FULL_c128_z80_40col_turn_based.d64 -write a80tb.ldr
	$(TOOLS_PATH)/generic/c1541 -attach ALT_FULL_c128_z80_40col_turn_based.d64 -write a80tb
	mv ALT_FULL_c128_z80_40col_turn_based.d64 $(BUILD_PATH)/
	rm A80TB.LDR
	rm A80TB
	rm a80tb.bin



#############################
# CAMPUTERS LYNX
camputers_lynx_tiny:
	$(Z88DK_PATH)$(MYZ88DK) +lynx $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-pragma-redirect:fputc_cons=fputc_cons_generic \
	-pragma-redirect:getk=getk_inkey \
	-D__CAMPUTERS_LYNX__ \
	-vn \
	-DCONIO_VT52 \
	-DNO_COLOR \
	-DTINY_GAME \
	-lndos \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(TINY_FILES) \
	-create-app -o $(BUILD_PATH)/ALT_TINY_camputers_lynx.bin
	rm $(BUILD_PATH)/ALT_TINY_camputers_lynx.bin


#############################
# CPM
cpm_z80_tiny_buffered:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-DSTDLIB \
	-DFORCE_XSIZE=24 \
	-DFORCE_YSIZE=16 \
	-DNO_COLOR \
	-DTINY_GAME \
	-DTURN_BASED \
	-DBUFFERED \
	-DNO_INIT_GRAPHICS \
	-DALT_PRINT \
	-DDEFAULT_CLEAR_SCREEN \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(TINY_FILES) \
	-create-app -o$(BUILD_PATH)/ALT_FULL_cpm_z80_tiny_buffered.bin 
	rm $(BUILD_PATH)/ALT_FULL_cpm_z80_tiny_buffered.bin 


# cannot run in Mame (Kaypro 2x)
cpm_z80_buffered:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-DSTDLIB \
	-DFORCE_XSIZE=24 \
	-DFORCE_YSIZE=16 \
	-DNO_COLOR \
	-DFULL_GAME \
	-DTURN_BASED \
	-DBUFFERED \
	-DNO_INIT_GRAPHICS \
	-DALT_PRINT \
	-DDEFAULT_CLEAR_SCREEN \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(FULL_FILES) \
	-create-app -o$(BUILD_PATH)/ALT_FULL_cpm_z80_buffered.bin 
	rm $(BUILD_PATH)/ALT_FULL_cpm_z80_buffered.bin 


cpm_z80_vt52:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-DCONIO_VT52 \
	-D__CPM_80X24__ \
	-DFULL_GAME -DLESS_TEXT -DNO_SLEEP -DNO_WAIT \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DEND_SCREEN -DBETWEEN_LEVEL \
	-create-app -o$(BUILD_PATH)/ALT_FULL_cpm_vt52.bin \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	rm $(BUILD_PATH)/ALT_FULL_cpm_vt52.bin	


cpm_z80_vt100:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-DCONIO_VT100 \
	-D__CPM_80X24__ \
	-DFULL_GAME -DLESS_TEXT -DNO_SLEEP -DNO_WAIT \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DEND_SCREEN -DBETWEEN_LEVEL \
	-create-app -o$(BUILD_PATH)/ALT_FULL_cpm_vt100.bin \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	rm $(BUILD_PATH)/ALT_FULL_cpm_vt100.bin	


#############################
# EG2K
eg2k_no_gfx:
	$(Z88DK_PATH)$(MYZ88DK) +trs80 $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-D__EG2K__ \
	-subtype=eg2000disk \
	-lndos \
	-lm \
	-D__TRS80__ \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DFULL_GAME -DBETWEEN_LEVEL -DEND_SCREEN \
	-DCONIO_VT52 \
	-create-app -o eg2kngfx.bin \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	mv eg2kngfx.cmd $(BUILD_PATH)/ALT_FULL_eg2k_no_gfx.cmd
	rm eg2kngfx.bin


#############################
# FP1100
fp1100_tiny:
	$(Z88DK_PATH)$(MYZ88DK) +fp1100 $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-pragma-redirect:fputc_cons=fputc_cons_generic \
	-D__FP1100__ -vn \
	-DCONIO_VT52 \
	-DTINY_GAME -DSOUNDS \
	-lndos \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(TINY_FILES) \
	-create-app -o fp1100t.bin
	mv fp1100t.d88 $(BUILD_PATH)/ALT_TINY_fp1100.d88
	rm fp1100t.bin
	rm fp1100t_BOOTSTRAP.bin


#############################
# G800
g800_tiny_turn_based:
	$(Z88DK_PATH)$(MYZ88DK) +g800 $(SCCZ80_OPTS) -clib=g850b $(INCLUDE_OPTS) \
	-D__G800__ \
	-DTURN_BASED \
	-DNO_BLINKING \
	-vn \
	-DFORCE_CONIO_LIB \
	-DTINY_GAME \
	-lndos \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(TINY_FILES) \
	-create-app -o g800ttb.bin
	rm g800ttb.bin
	rm g800ttb.rom
	mv g800ttb.ihx $(BUILD_PATH)/ALT_TINY_g800_turn_based.ihx


