# ------------------------------------------------------------------------------------------
# TMS9000-GCC
#   


# Paths to TMS9900 compilation tools 
# ( Set in environment to override paths )
TMS9900_DIR?=/opt/gcc4ti/bin
ELF2EA5_DIR?=/home/fabri/Retro/GCC4TI/elf2ea5
EA5_SPLIT_DIR?=/home/fabri/Retro/GCC4TI/ea5split
CLASSIC99_DSK1?=/home/fabri/Retro/GCC4TI/DSK1


# Full paths to the executables used
GAS=$(TMS9900_DIR)/tms9900-as
LD=$(TMS9900_DIR)/tms9900-ld
CC=$(TMS9900_DIR)/tms9900-gcc
AR=$(TMS9900_DIR)/tms9900-ar
ELF2EA5=$(ELF2EA5_DIR)/elf2ea5
EA5_SPLIT=$(EA5_SPLIT_DIR)/ea5split

LDFLAGS_EA5=\
  --section-start .text=a000 --section-start .data=2080 -M



C_FLAGS=\
  -O2 -std=c99 -s -I./ -fno-builtin



# test: library testlib.o $(OBJECT_LIST_EA5) 
	# $(LD) $(OBJECT_LIST_EA5) testlib.o $(LDFLAGS_EA5) -L. -lti99 -o testlib.ea5.elf > ea5.map
	# $(ELF2EA5) testlib.ea5.elf testlib.ea5.bin
	# $(EA5_SPLIT) testlib.ea5.bin
	# cp TESTLI* $(CLASSIC99_DSK1)



TI99_CC ?= tms9900-gcc 
TI99_TURN_BASED_OPTS ?= \
	$(C_FLAGS) $(GLOBAL_OPTS) \
	-D__TI99__ -nostdlib -DNO_RANDOM_LEVEL \
	-DXSize=32 \
	-DYSize=22 \
	-DALT_SLEEP \
	-DTURN-BASED \
	-DTINY_GAME -DNO_WALL \
	-D_XL_NO_WAIT \
	-D_XL_NO_COLOR \
	-DCONIO \
	-DNO_SET_SCREEN_COLORS \
	-DDEFAULT_CLEAR_SCREEN \
	-D_XL_SLOW_DOWN_FACTOR=50000


TI99_OPTS ?= \
	$(C_FLAGS) $(GLOBAL_OPTS) \
	-D__TI99__ -nostdlib -DNO_RANDOM_LEVEL \
	-DXSize=32 \
	-DYSize=22 \
	-DALT_SLEEP \
	-DTINY_GAME -DNO_WALL \
	-D_XL_NO_WAIT \
	-DCONIO -D_XL_NO_COLOR \
	-DNO_SET_SCREEN_COLORS \
	-DDEFAULT_CLEAR_SCREEN \
	-D_XL_SLOW_DOWN_FACTOR=65000


##################################################################################################

# Paths to TMS9900 compilation tools
GAS=tms9900-as
LD=tms9900-ld
TI99CC=tms9900-gcc
CXX=tms9900-c++
OBJCOPY=tms9900-objcopy

LIB_TI99_PATH=$(TMS9900-GCC_PATH)/../lib

# Flags used during linking
# Refer to the linker rules in an external file
LDFLAGS=\
  --script=$(CFG_PATH)gcc4ti99/linkfile.cfg 

# List of compiled objects used in executable
OBJECT_LIST= \
  $(TOOLS_PATH)/ti99/crt0_ea5.o \
  $(SOURCE_PATH)/../../debug/ti99_test.o
  
OBJECT_LIST_TURN_BASED= \
  $(TOOLS_PATH)/ti99/crt0_ea5.o \
  $(SOURCE_PATH)/../../debug/ti99_test.o

TI99_INCLUDE_OPTS ?= $(INCLUDE_OPTS) -I$(TMS9900-GCC_PATH)/../include

# Recipes to compile individual files
%.o: %.asm
	$(GAS) $< -o $@
%.o: %.c
	$(TI99CC) $(TI99_INCLUDE_OPTS) $(TI99_OPTS) -c $< -o $@

# List of all files needed in executable
PREREQUISITES=\
  $(OBJECT_LIST)

xchase.ea5.elf: $(PREREQUISITES)
	$(LD) $(OBJECT_LIST) $(LDFLAGS_EA5) -L$(LIB_TI99_PATH) -lti99 -o xchase.ea5.elf > xchase.map


# Recipe to compile the executable
ti99_test: xchase.ea5.elf $(TOOLS_PATH)/ti99/elf2ea5$(COMPILEDEXT) $(TOOLS_PATH)/ti99/ea5split$(COMPILEDEXT)
	$(TOOLS_PATH)/ti99/elf2ea5$(COMPILEDEXT) xchase.ea5.elf xchase.ea5.bin
	$(TOOLS_PATH)/ti99/ea5split$(COMPILEDEXT) xchase.ea5.bin
	rm -rf xchase.map
	rm -rf ea5.map
	rm -rf xchase.ea5.elf
	mv XCHASE $(BUILD_PATH)/ti99ConioTest
	rm -rf xchase.ea5.bin


gcc_ti99_targets: \
	ti99_targets


# Recipe to clean all compiled objects
.phony ti99clean:
	rm -f *.o
	rm -f *.elf
	rm -f *.cart


