#

COCO_COLOR_GFX_GAME_OPTS ?= 
#-DMAX_ROCKETS_ON_SCREEN=7 -DFASTER_WALL_REDRAW -DMAX_NUMBER_OF_MISSILES=3

CREATIVISION_GAME_OPTS ?= -DMAX_NUMBER_OF_MISSILES=2 -DMAX_ROCKETS_ON_SCREEN=7 -DNO_BOTTOM_WALL_REDRAW

GAMATE_GAME_OPTS ?= -DMAX_NUMBER_OF_MISSILES=3 -DMAX_ROCKETS_ON_SCREEN=4 
#-DNO_BOTTOM_WALL_REDRAW -DNO_EXTRA_TITLE

C128_Z80_80COL_GAME_OPTS ?= -DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=4  -DNO_BOTTOM_WALL_REDRAW 
    
ZX81_NO_GFX_GAME_OPTS ?= -DMAX_ROCKETS_ON_SCREEN=7 -DMAX_NUMBER_OF_MISSILES=4 -DMISSILE_DROP_LOOP_MASK=1 -DSMALL_WALL 

ZX81_GFX_GAME_OPTS ?= -DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=2 -DMISSILE_DROP_LOOP_MASK=7 -DSMALL_WALL -DNO_BOTTOM_WALL_REDRAW -DNO_EXTRA_TITLE

APPLE2_GAME_OPTS ?= -DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=4

COMX_GAME_OPTS ?= 	-DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=3 -DMISSILE_DROP_LOOP_MASK=1 -DSMALL_WALL -DNO_BOTTOM_WALL_REDRAW -DNORMAL_ZOMBIE_SPEED=1 -DSLOW_ZOMBIE_SPEED=7

PECOM_GAME_OPTS ?= 	-DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=3 -DSMALL_WALL -DNO_BOTTOM_WALL_REDRAW -DNORMAL_ZOMBIE_SPEED=1 -DSLOW_ZOMBIE_SPEED=7

TMC600_GAME_OPTS ?= 	-DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=4 -DSMALL_WALL -DNO_BOTTOM_WALL_REDRAW -DNORMAL_ZOMBIE_SPEED=1 -DSLOW_ZOMBIE_SPEED=7

CPC_GAME_OPTS ?= -DMAX_ROCKETS_ON_SCREEN=6 -DMAX_NUMBER_OF_MISSILES=4

CAMPUTERS_LYNX_GAME_OPTS ?= -DMAX_ROCKETS_ON_SCREEN=5 -DMAX_NUMBER_OF_MISSILES=3

NCURSES_GAME_OPTS ?= -DNO_EXTRA_TITLE