


# -o$(BUILD_PATH)/TINY_abc800.bin 	
abc800_tiny:
	$(Z88DK_PATH)$(MYZ88DK) +abc800 $(SCCZ80_OPTS) -zorg=40000 \
	-D__ABC800__ \
	-DCONIO_ADM3A \
	-DTINY_GAME -DLESS_TEXT -DNO_SLEEP \
	-o$(BUILD_PATH)/TINY_abc800.bin \
	$(SOURCE_PATH)/display_macros.c \
	$(SOURCE_PATH)/enemy.c \
	$(SOURCE_PATH)/level.c $(SOURCE_PATH)/character.c $(SOURCE_PATH)/game_text.c  \
	$(SOURCE_PATH)/strategy.c $(SOURCE_PATH)/input_macros.c \
	$(SOURCE_PATH)/main.c


abc800_light:
	$(Z88DK_PATH)$(MYZ88DK) +abc800 $(SCCZ80_OPTS) -lm \
	-zorg=49200 $(INCLUDE_OPTS) \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DCONIO_VT100 \
	-DNO_WAIT \
	-D__ABC80__ -vn  -lndos  \
	$(LIGHT_FILES)
	$(TOOLS_PATH)/z88dk/abc80/bin2bac2$(COMPILEDEXT) -800 a.bin $(BUILD_PATH)/LIGHT_ABC800.bac 49200	
	mv a.bin $(BUILD_PATH)/LIGHT_abc800.bin 


abc800:
	$(Z88DK_PATH)$(MYZ88DK) +abc800 $(SCCZ80_OPTS) -lm -subtype=hex -zorg=49200 \
	$(INCLUDE_OPTS) \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_clib.inc \
	-DFORCE_CONIO_LIB \
	-D__ABC800__  -vn -DFULL_GAME \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DLESS_TEXT \
	-DSIMPLE_STRATEGY \
	-DNO_BLINKING \
	-DNO_HINTS \
	-DNO_WAIT \
	-DNO_BORDER \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_RANDOM_LEVEL \
	-DNO_SET_SCREEN_COLORS \
	-DNO_SLEEP \
	-DFLAT_ENEMIES \
	-lndos -create-app \
	$(FULL_FILES)
	$(TOOLS_PATH)/z88dk/abc80/bin2bac2$(COMPILEDEXT) a.bin $(BUILD_PATH)/xchase.bac 49200
	$(TOOLS_PATH)/z88dk/abc80/dosgen$(COMPILEDEXT) $(BUILD_PATH)/FULL_abc800.dsk 
	$(TOOLS_PATH)/z88dk/abc80/doscopy$(COMPILEDEXT) $(BUILD_PATH)/FULL_abc800.dsk -b $(BUILD_PATH)/xchase.bac
	rm a.bin 
	rm $(BUILD_PATH)/xchase.bac
	mv a.ihx $(BUILD_PATH)/FULL_abc800.ihx 	


abc800_32k:
	$(Z88DK_PATH)$(MYZ88DK) +abc800 $(SCCZ80_OPTS) -lm  $(INCLUDE_OPTS) \
	-D__ABC80__ -vn -DFULL_GAME -DSOUNDS  -DEND_SCREEN -DBETWEEN_LEVEL \
	-DCONIO -DFORCE_CONIO_LIB -DNO_INIT_GRAPHICS \
	-lndos \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)


c7420:
	$(Z88DK_PATH)$(MYZ88DK) +c7420 $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-lndos \
	-DSTDLIB \
	-DNO_COLOR \
	-DBUFFERED -DALT_PRINT \
	-DFULL_GAME -DLESS_TEXT -DNO_SLEEP -DNO_WAIT \
	-DNO_INIT_GRAPHICS \
	-create-app \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(FULL_FILES)
	rm a.bin
	mv _a.bas $(BUILD_PATH)/FULL_c7420.bas	


c7420_tiny:
	$(Z88DK_PATH)$(MYZ88DK) +c7420 $(SCCZ80_OPTS) \
	$(INCLUDE_OPTS) \
	-lndos \
	-DSTDLIB \
	-DNO_COLOR \
	-DBUFFERED -DALT_PRINT \
	-DTINY_GAME -DLESS_TEXT -DNO_SLEEP -DNO_WAIT \
	-DNO_INIT_GRAPHICS \
	-create-app \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(TINY_FILES)
	rm a.bin
	mv _a.bas $(BUILD_PATH)/TINY_c7420.bas


gamegear_tiny_buffered:
	$(Z88DK_PATH)$(MYZ88DK) +sms $(SCCZ80_OPTS) -lgamegear -clib=sdcc_iy -startup=17 \
	$(INCLUDE_OPTS) \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_sms.inc \
	-DFORCE_XSIZE=20 \
	-DFORCE_YSIZE=16 \
	-D__SMS__ \
	-DNO_COLOR \
	-DTINY_GAME \
	-DSTDLIB \
	-DLESS_TEXT \
	-create-app \
	-DBUFFERED \
	-DTURN_BASED \
	-DALT_PRINT \
	-DDEFAULT_CLEAR_SCREEN \
	-DNO_SLEEP \
	-DNO_WAIT \
	-o $(BUILD_PATH)/TINY_gamegear_buffered.bin \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/sms/sms_init_graphics.c \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(TINY_FILES)
	rm $(BUILD_PATH)/TINY_gamegear_buffered_CODE.bin
	rm $(BUILD_PATH)/TINY_gamegear_buffered_DATA.bin
	rm $(BUILD_PATH)/TINY_gamegear_buffered_BSS.bin
	rm $(BUILD_PATH)/TINY_gamegear_buffered_UNASSIGNED.bin


kc_tiny_putc4x6:
	$(Z88DK_PATH)$(MYZ88DK) +kc $(SCCZ80_OPTS) -subtype=tap \
	\
	-D__KC__ \
	-DTINY_GAME -DLESS_TEXT -DNO_SLEEP \
	-DZ88DK_PUTC4X6 \
	-DCONIO \
	-DALT_PRINT \
	-DNO_INIT_GRAPHICS \
	-create-app -o$(BUILD_PATH)/ALT_TINY_kc_putc4x6_.bin \
	$(TINY_FILES) \
	$(CROSS_LIB_PATH)/display/alt_print/z88dk_putc4x6_alt_print.c
	rm $(BUILD_PATH)/ALT_TINY_kc_putc4x6_.bin


m100:
	$(Z88DK_PATH)$(MYZ88DK) +m100 $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__M100__ \
	-DFORCE_XSIZE=32 \
	-DFORCE_YSIZE=24 \
	-DNO_SET_SCREEN_COLORS \
	-DNO_COLOR \
	-DFULL_GAME  \
	-DCONIO_VT52 \
	-DCONIO \
	-lndos \
	-DNO_INIT_GRAPHICS \
	$(FULL_FILES) \
	-create-app -o$(BUILD_PATH)/FULL_m100.bin
	rm $(BUILD_PATH)/FULL_m100.bin


mz2500_buffered:
	$(Z88DK_PATH)$(MYZ88DK) +mz2500 $(ZSDCC_OPTS) \
	$(INCLUDE_OPTS) \
	-compiler=sdcc \
	-DFORCE_XSIZE=16 \
	-DFORCE_YSIZE=12 \
	-DFORCE_GHOSTS_NUMBER=8 \
	-D__MZ2500__ \
	-v \
	-DFULL_GAME \
	-DNO_SET_SCREEN_COLORS \
	-lndos \
	-DNO_INIT_GRAPHICS \
	-DFORCE_NARROW \
	-DFORCE_CONIO_LIB -DCONIO \
	-pragma-include:$(CFG_PATH)/z88dk/zpragma_clib.inc \
	$(FULL_FILES) \
	-create-app 
	mv a.dsk $(BUILD_PATH)/ALT_FULL_mz2500_buffered.dsk
	rm a.bin




px4_putc4x6:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) -lpx4 \
	$(INCLUDE_OPTS) \
	-pragma-define:ansicolumns=40 \
	-pragma-define:ansipixels=240 -pragma-define:ansicolumns=60 \
 	-subtype=px4ansi \
	-D__PX4__ \
	-DFULL_GAME \
	-DNO_WAIT \
	-DBETWEEN_LEVEL -DEND_SCREEN \
	-DZ88DK_PUTC4X6 \
	-DNO_PRINT \
	-DCONIO -DNO_INIT_GRAPHICS \
	-Cz–-32k \
	-create-app \
	-vn -lndos \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	rm a.bin
	mv A.ROM $(BUILD_PATH)/FULL_px4_putc4x6.ROM


px4_tiny_putc4x6:
	$(Z88DK_PATH)$(MYZ88DK) +cpm $(SCCZ80_OPTS) -lpx4 \
	$(INCLUDE_OPTS) \
	-pragma-define:ansicolumns=40 \
	-pragma-define:ansipixels=240 -pragma-define:ansicolumns=60 \
 	-subtype=px4ansi \
	-D__PX4__ \
	-DTINY_GAME \
	-DNO_WAIT \
	-DZ88DK_PUTC4X6 \
	-DCONIO -DNO_INIT_GRAPHICS \
	-Cz–-32k \
	-create-app \
	-vn -lndos \
	$(TINY_FILES)
	rm a.bin
	mv A.ROM $(BUILD_PATH)/TINY_px4_putc4x6.ROM


rc2014:
	$(Z88DK_PATH)$(MYZ88DK) +rc2014 $(SCCZ80_OPTS)  $(INCLUDE_OPTS) \
	-D__ZXN__ \
	-DFORCE_XSIZE=32 \
	-DFORCE_YSIZE=24 \
	-DNO_SET_SCREEN_COLORS \
	-DNO_COLOR \
	-DFULL_GAME  \
	-DCONIO_VT52 \
	-DCONIO \
	-lndos \
	-DNO_INIT_GRAPHICS \
	$(FULL_FILES) \
	-create-app -o$(BUILD_PATH)/FULL_rc2014.bin


rex:
	$(Z88DK_PATH)$(MYZ88DK) +rex $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__REX__ \
	-DTURN_BASED \
	-vn \
	-DREX \
	-DSTDLIB \
	-DNO_COLOR \
	-DFULL_GAME -DSOUNDS \
	-lndos \
	-DNO_PRINT \
	-DNO_WAIT \
	-DNO_SLEEP \
	-DNO_INPUT \
	-DNO_INIT_GRAPHICS \
	-DDEFAULT_CLEAR_SCREEN \
	$(FULL_FILES) \
	-create-app -o $(BUILD_PATH)/FULL_rex.bin
	rm $(BUILD_PATH)/FULL_rex_BSS.bin
	rm $(BUILD_PATH)/FULL_rex.bin


rex_buffered:
	$(Z88DK_PATH)$(MYZ88DK) +rex $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__REX__ \
	-DTURN_BASED \
	-vn \
	-DBUFFERED \
	-DSTDLIB \
	-DNO_COLOR \
	-DFULL_GAME -DSOUNDS \
	-lndos \
	-DNO_PRINT \
	-DNO_WAIT \
	-DNO_SLEEP \
	-DNO_INPUT \
	-DNO_INIT_GRAPHICS \
	-DDEFAULT_CLEAR_SCREEN \
	$(FULL_FILES) \
	-create-app -o $(BUILD_PATH)/FULL_rex_buffered.bin
	rm $(BUILD_PATH)/FULL_rex_buffered_BSS.bin
	rm $(BUILD_PATH)/FULL_rex_buffered.bin


special:
	$(Z88DK_PATH)$(MYZ88DK) +special $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__SPECIAL__ \
	-DFORCE_XSIZE=48 \
	-DFORCE_YSIZE=32 \
	-DNO_SET_SCREEN_COLORS \
	-DNO_COLOR \
	-DFULL_GAME  \
	-DCONIO_VT52 \
	-DCONIO \
	-lndos \
	-DNO_INIT_GRAPHICS \
	$(FULL_FILES) \
	-create-app -o$(BUILD_PATH)/FULL_special.bin
	rm $(BUILD_PATH)/FULL_special.bin


x07_tiny:
	$(Z88DK_PATH)$(MYZ88DK) +x07 $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-Cz--audio \
	-DFORCE_BOMBS_NUMBER=2 \
	-DFORCE_GHOSTS_NUMBER=6 \
	-DLESS_TEXT \
	-DNO_BLINKING \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_RANDOM_LEVEL \
	-DNO_SET_SCREEN_COLORS \
	-D__X07__ \
	-vn \
	-DCONIO_VT52 \
	-DNO_COLOR \
	-DTINY_GAME \
	-lndos \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(TINY_FILES) \
	-create-app -o $(BUILD_PATH)/TINY_x07.bin
	rm $(BUILD_PATH)/TINY_x07.bin


yaz180:
	$(Z88DK_PATH)$(MYZ88DK) +yaz180 $(SCCZ80_OPTS) $(INCLUDE_OPTS) \
	-D__ZXN__ \
	-DFORCE_XSIZE=32 \
	-DFORCE_YSIZE=24 \
	-DNO_SET_SCREEN_COLORS \
	-DNO_COLOR \
	-DFULL_GAME  \
	-DCONIO_VT52 \
	-DCONIO \
	-lndos \
	-DNO_INIT_GRAPHICS \
	$(FULL_FILES) \
	-create-app -o$(BUILD_PATH)/FULL_yaz180.bin


zx80_16k:
	$(Z88DK_PATH)$(MYZ88DK) +zx80 $(SCCZ80_OPTS) $(INCLUDE_OPTS) -vn \
	-D__ZX80__ -DFULL_GAME \
	-DEND_SCREEN \
	-DALT_SLEEP \
	-DCONIO \
	-DZX80_GEN_TV_FIELD \
	-lndos \
	-create-app -o  $(BUILD_PATH)/FULL_zx80_16k.prg \
	$(CROSS_LIB_PATH)/display/init_graphics/z88dk/zx80/zx80_init_graphics.c \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES)
	rm $(BUILD_PATH)/FULL_zx80_16k.prg
