# -----------------------------------------------
# CC65


cc65_alt_targets: \
    atari_alt_targets \
    atari_lynx_alt_targets \
    c16_alt_targets \
    creativision_alt_targets \
    gamate_alt_targets \
    nes_no_fx \
    pet_alt_targets \
    vic20_alt_targets


#############################
# ATARI 8-bit

atari_alt_targets: \
    atari_no_color_16k_full \
    atari_no_color_16k


#############################
# ATARI LYNX

atari_lynx_alt_targets: \
    atari_lynx_light 


#############################
# C16

c16_alt_targets: \
    c16_16k_no_gfx \
    c16_16k_full_no_gfx \
    c16_16k_light


#############################
# CREATIVISION
creativision_alt_targets: \
    creativision_32k \
    creativision_16k_m \
    creativision_16k_x


#############################
# GAMATE

gamate_alt_targets: \
    gamate_tiny \
    gamate_light


#############################
# CREATIVISION

nes_alt_targets: \
    nes_no_fx


#############################
# PET

pet_alt_targets: \
    pet_8k_buffered \
    pet_8k_light_experimental


#############################
# VIC 20

vic20_alt_targets: \
    vic20_exp_3k_light \
    vic20_exp_8k_full \
    vic20_exp_8k_old \
    vic20_unexpanded_no_gfx \
    vic20_unexpanded_turn_based


###############################################################

#############################
# ATARI 8-BIT

atari_no_color_16k_full: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -Cl -t atari \
	-DFULL_GAME \
	-DNO_HINTS \
	-DNO_BLINKING \
	-DLESS_TEXT \
	-DFLAT_ENEMIES \
	-DALT_SLEEP \
	-DNO_RANDOM_LEVEL \
	-DNO_MESSAGE \
	-DNO_PRINT -DCONIO \
	-DNO_INIT_GRAPHICS \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(FULL_FILES) -o $(BUILD_PATH)/ALT_FULL_atari_no_color_16k.xex	


atari_no_color_16k: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -Cl -t atari \
	-DLESS_TEXT \
	-DNO_BLINKING \
	-DNO_RANDOM_LEVEL \
	-DNO_PRINT \
	-DNO_MESSAGE -DCONIO -DNO_INIT_GRAPHICS \
	$(LIGHT_FILES) \
	-o $(BUILD_PATH)/ALT_LIGHT_atari_no_color_16k.xex


#############################
# ATARI 8-BIT
atari_lynx_light:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t lynx \
	-DNO_SET_SCREEN_COLORS \
	-D__ATARI_LYNX__ \
	-DNO_PRINT \
	-DNO_SLEEP \
	-DTGI \
	-DDEFAULT_CLEAR_SCREEN \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/atari_lynx/atari_lynx_init_graphics.c \
	$(LIGHT_FILES) \
	-o $(BUILD_PATH)/ALT_LIGHT_ATARI_LYNX.lnx


#############################
# C16


c16_16k_no_gfx:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -t c16 -Cl \
	-DFULL_GAME -DNO_INIT_GRAPHICS -DLESS_TEXT -DUSE_MEMORY_BUFFERS -DNO_SLEEP -DSOUNDS -DMEMORY_MAPPED  \
	--config $(CFG_PATH)/cc65/c16-16k.cfg \
	$(CROSS_LIB_PATH)/sound/cc65/c264/c264_sounds.c  \
	$(CROSS_LIB_PATH)/memory/c16_memory.s \
	$(FULL_FILES) -o $(BUILD_PATH)/ALT_FULL_c16_16k_no_gfx.prg

c16_16k_light: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -t c16 \
	--config $(CFG_PATH)/cc65/c16-16k_GFX.cfg \
	-DANIMATE_PLAYER  -DSOUNDS \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DREDEFINED_CHARS \
	-DCONIO \
	-DUSE_MEMORY_BUFFERS \
	$(CROSS_LIB_PATH)/sound/cc65/c264/c264_sounds.c \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/c264/c16_32k_redefined_chars_init_graphics.c  \
	$(LIGHT_FILES) \
	$(CROSS_LIB_PATH)/memory/c16_memory.s \
	-o $(BUILD_PATH)/ALT_LIGHT_c16_16k.prg

c16_16k_full_no_gfx: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -Cl -t c16 \
	--config $(CFG_PATH)/cc65/c16-16k.cfg \
	-DFULL_GAME \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DLESS_TEXT	\
	-DSOUNDS \
	-DALT_PRINT \
	-DANIMATE_PLAYER \
	-DMEMORY_MAPPED \
	-DEND_SCREEN \
	-DUSE_MEMORY_BUFFERS \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/c264/c264_init_graphics.c \
	$(CROSS_LIB_PATH)/sound/cc65/c264/c264_sounds.c \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/memory/c16_memory.s \
	-o $(BUILD_PATH)/ALT_FULL_c16_16k_no_gfx.prg	

#############################
# CREATIVISION

creativision_32k:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t creativision \
	-DNO_SLEEP -DLESS_TEXT -DFULL_GAME -DBETWEEN_LEVEL -DEND_SCREEN -DMEMORY_MAPPED -DNO_INIT_GRAPHICS \
	--config $(CFG_PATH)/cc65/creativision-32k.cfg \
	$(FULL_FILES) \
	$(SOURCE_PATH)/end_screen.c \
	-o $(BUILD_PATH)/ALT_FULL_creativision_32k.bin


creativision_16k_m:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t creativision \
	-DNO_SET_SCREEN_COLORS \
	-DFULL_GAME -DALT_SLEEP \
	-DSIMPLE_STRATEGY \
	-DMEMORY_MAPPED \
	-DANIMATE_PLAYER \
	--config $(CFG_PATH)/cc65/creativision-16k.cfg \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/creativision/creativision_init_graphics.c \
	-o $(BUILD_PATH)/FULL_creativision_16k.bin	
	dd if=$(BUILD_PATH)/FULL_creativision_16k.bin ibs=1 count=8192 of=$(BUILD_PATH)/FULL_creativision_16k_LOW.bin
	dd if=$(BUILD_PATH)/FULL_creativision_16k.bin ibs=1 skip=8192 of=$(BUILD_PATH)/FULL_creativision_16k_HIGH.bin
	rm $(BUILD_PATH)/FULL_creativision_16k.bin 
	cat $(BUILD_PATH)/FULL_creativision_16k_HIGH.bin $(BUILD_PATH)/FULL_creativision_16k_LOW.bin > $(BUILD_PATH)/ALT_FULL_creativision_16k_SWAPPED.bin
	rm $(BUILD_PATH)/FULL_creativision_16k_LOW.bin
	rm $(BUILD_PATH)/FULL_creativision_16k_HIGH.bin	      


creativision_16k_x:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t creativision \
	-DNO_SET_SCREEN_COLORS \
	-DFULL_GAME -DALT_SLEEP \
	-DSIMPLE_STRATEGY \
	-DCONIO \
	-DANIMATE_PLAYER \
	--config $(CFG_PATH)/cc65/creativision-16k.cfg \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/creativision/creativision_init_graphics.c \
	-o $(BUILD_PATH)/FULL_creativision_16k.bin	
	dd if=$(BUILD_PATH)/FULL_creativision_16k.bin ibs=1 count=8192 of=$(BUILD_PATH)/FULL_creativision_16k_LOW.bin
	dd if=$(BUILD_PATH)/FULL_creativision_16k.bin ibs=1 skip=8192 of=$(BUILD_PATH)/FULL_creativision_16k_HIGH.bin
	rm $(BUILD_PATH)/FULL_creativision_16k.bin 
	cat $(BUILD_PATH)/FULL_creativision_16k_HIGH.bin $(BUILD_PATH)/FULL_creativision_16k_LOW.bin > $(BUILD_PATH)/ALT_FULL_creativision_16k_SWAPPED.bin
	rm $(BUILD_PATH)/FULL_creativision_16k_LOW.bin
	rm $(BUILD_PATH)/FULL_creativision_16k_HIGH.bin
#############################
# GAMATE


gamate_light: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t gamate \
	-DLESS_TEXT \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DFORCE_GHOSTS_NUMBER=7 \
	-DSIMPLE_STRATEGY \
	$(LIGHT_FILES) \
	-o $(BUILD_PATH)/ALT_LIGHT_gamate.bin
	$(TOOLS_PATH)/cc65/gamate/gamate-fixcart $(BUILD_PATH)/ALT_LIGHT_gamate.bin
	
gamate_tiny: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t gamate \
	-DTINY_GAME \
	-DLESS_TEXT \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DFORCE_GHOSTS_NUMBER=7 \
	-DSIMPLE_STRATEGY \
	$(TINY_FILES) \
	-o $(BUILD_PATH)/ALT_TINY_gamate.bin
	$(TOOLS_PATH)/cc65/gamate/gamate-fixcart $(BUILD_PATH)/ALT_TINY_gamate.bin


#############################
# NES

nes_no_fx: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t nes \
	-DFULL_GAME \
	-DBETWEEN_LEVEL -DEND_SCREEN \
	-DCONIO -DNO_INIT_GRAPHICS \
	$(SOURCE_PATH)/end_screen.c \
	$(FULL_FILES) \
	-o $(BUILD_PATH)/ALT_FULL_nes_no_fx.nes	


#############################
# PCE

pce_light:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -t pce -Cl \
	--config $(CFG_PATH)cc65/pce_8k_less_stack.cfg \
	-DLESS_TEXT \
	-DNO_MESSAGE -DNO_BLINKING \
	-DNO_CONTROL_INSTRUCTIONS -DNO_INITIAL_SCREEN \
	-DNO_DEAD_GHOSTS -DNO_SET_SCREEN_COLORS -DNO_RANDOM_LEVEL \
	-DFORCE_GHOSTS_NUMBER=6 \
	-DFORCE_NARROW \
	-DCONIO -DNO_INIT_GRAPHICS \
	-DNO_STATS \
	$(LIGHT_FILES) \
	-o $(BUILD_PATH)/ALT_LIGHT_pce.pce


#############################
# PET

pet_8k_buffered: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -O -t pet -Cl \
	-DTINY_GAME -DNO_INIT_GRAPHICS \
	-DBUFFERED \
	-DALT_PRINT \
	-DUSE_TINY_MEMORY_BUFFERS \
	$(TINY_FILES) \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(CROSS_LIB_PATH)/memory/pet_memory.s \
	-o $(BUILD_PATH)/ALT_TINY_pet_8k_buffered.prg	


pet_8k_light_experimental:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -t pet -Cl \
	-DNO_INIT_GRAPHICS -DCONIO -DLESS_TEXT -DNO_HINTS -DNO_BLINKING -DNO_RANDOM_LEVEL \
	-DUSE_LIGHT_MEMORY_BUFFERS \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DFORCE_NARROW \
	-DNO_SET_SCREEN_COLORS \
	-DNO_STATS \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_DEAD_GHOSTS \
	$(LIGHT_FILES) \
	$(CROSS_LIB_PATH)/memory/pet_memory.s \
	-o $(BUILD_PATH)/ALT_LIGHT_pet_8k_experimental.prg


#############################
# VIC 20
vic20_exp_3k_light:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -Cl -t vic20 \
	--config $(CFG_PATH)/cc65/alt/vic20-3k.cfg  \
	-DANIMATE_PLAYER -DFORCE_GHOSTS_NUMBER=8 \
	-DSOUNDS \
	-DCC65_GOTO \
	-DNO_PRINT \
	-DVIC20_EXP_3K \
	-DMEMORY_MAPPED \
	-DCBM_SCREEN_CODES \
	-DUSE_LIGHT_MEMORY_BUFFERS \
	-DNO_HINTS \
	-DNO_INITIAL_SCREEN \
	-DLESS_TEXT \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_MESSAGE \
	-DNO_TEXT_COLOR \
	-DNO_BLINKING \
	-DALT_SLEEP \
	-DALT_DISPLAY_STATS \
	-DALT_HIGHSCORE \
	-DDEFAULT_CLEAR_SCREEN \
	$(CROSS_LIB_PATH)/display/alt_print/simple_alt_stats.c \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/vic20/vic20_init_graphics.c \
	$(CROSS_LIB_PATH)/sound/cc65/vic20/vic20_sounds.c \
	$(LIGHT_FILES) \
	$(CROSS_LIB_PATH)/memory/vic20_memory.s \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	-o $(BUILD_PATH)/ALT_LIGHT_vic20_exp_3k_no_gfx.prg


vic20_exp_8k_full:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -Cl -t vic20 --config $(CFG_PATH)/cc65/alt/vic20-8k.cfg \
	-DFULL_GAME \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DSIMPLE_STRATEGY \
	-DLESS_TEXT	\
	-DALT_PRINT \
	-DNO_HINTS \
	-DSOUNDS \
	-DALT_SLEEP \
	-DANIMATE_PLAYER \
	-DMEMORY_MAPPED \
	-DVIC20_EXP_8K \
	-DEND_SCREEN \
	-DUSE_MEMORY_BUFFERS \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	$(CROSS_LIB_PATH)/sound/cc65/vic20/vic20_sounds.c \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/vic20/vic20_init_graphics.c \
	$(CROSS_LIB_PATH)/display/alt_print/memory_mapped_alt_print.c \
	$(FULL_FILES) \
	$(CROSS_LIB_PATH)/memory/vic20_memory.s \
	$(SOURCE_PATH)/end_screen.c \
	-o $(BUILD_PATH)/ALT_FULL_vic20_exp_8k_no_gfx.prg


vic20_exp_8k_old: 
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -Cl -t vic20  -DSOUNDS -DANIMATE_PLAYER --config $(CFG_PATH)/cc65/alt/vic20-8k_old_GFX.cfg \
	-DCONIO -DVIC20_EXP_8K \
	-DREDEFINED_CHARS \
	-DALT_SLEEP \
	-DSIMPLE_STRATEGY \
	-DNO_HINTS \
	-DUSE_LIGHT_MEMORY_BUFFERS \
	-DLESS_TEXT \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_BLINKING \
	-DNO_RANDOM_LEVEL \
	$(CROSS_LIB_PATH)/display/graphics_data/cc65/udc.s \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/vic20/vic20_init_graphics.c \
	$(CROSS_LIB_PATH)/sound/cc65/vic20/vic20_sounds.c \
	$(SOURCE_PATH)/level.c $(SOURCE_PATH)/character.c \
	$(SOURCE_PATH)/game_text.c  $(CROSS_LIB_PATH)/text/text_macros.c \
	$(SOURCE_PATH)/skull.c $(SOURCE_PATH)/ghost.c $(CROSS_LIB_PATH)/input/input_macros.c  \
	$(SOURCE_PATH)/strategy.c $(SOURCE_PATH)/bullet.c \
	$(SOURCE_PATH)/move_player.c \
	$(CROSS_LIB_PATH)/display/init_images.c \
	$(SOURCE_PATH)/item.c	\
	--code-name CODE2 \
	$(CROSS_LIB_PATH)/display/display_macros.c  \
	$(SOURCE_PATH)/main.c \
	$(CROSS_LIB_PATH)/memory/vic20_memory.s \
	$(CROSS_LIB_PATH)/sleep/sleep_macros.c \
	-o $(BUILD_PATH)/ALT_LIGHT_vic20_exp_8k.prg


vic20_unexpanded_no_gfx:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -Cl -t vic20 \
	-DSOUNDS \
	-DANIMATE_PLAYER \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_TEXT_COLOR \
	-DVIC20_UNEXPANDED \
	-DNO_SLEEP \
	-DLESS_TEXT \
	-DNO_SET_SCREEN_COLORS \
	-DTINY_GAME \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DNO_DEAD_GHOSTS \
	-DFORCE_BOMBS_NUMBER=4 \
	-DMEMORY_MAPPED \
	-DALT_DISPLAY_STATS \
	-DALT_HIGHSCORE \
	-DROUND_ENEMIES \
	-DUSE_TINY_MEMORY_BUFFERS \
	--config $(CFG_PATH)/cc65/alt/vic20_unexpanded.cfg  \
	$(TINY_FILES) \
	$(CROSS_LIB_PATH)/memory/vic20_memory.s \
	$(CROSS_LIB_PATH)/sound/cc65/vic20/vic20_sounds_3k.c \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/vic20/vic20_init_graphics.c \
	$(CROSS_LIB_PATH)/display/alt_print/simple_alt_stats.c \
	-o $(BUILD_PATH)/ALT_TINY_vic20_unexpanded_no_gfx.prg


vic20_unexpanded_turn_based:
	$(CC65_PATH)$(MYCC65) $(INCLUDE_OPTS) -Or -Cl -t vic20 \
	-DSOUNDS \
	-DFORCE_KEYBOARD \
	-DTURN_BASED \
	-DNO_CONTROL_INSTRUCTIONS \
	-DNO_TEXT_COLOR \
	-DVIC20_UNEXPANDED \
	-DNO_SLEEP \
	-DLESS_TEXT \
	-DNO_SET_SCREEN_COLORS \
	-DTINY_GAME \
	-DNO_RANDOM_LEVEL \
	-DNO_STATS \
	-DFORCE_GHOSTS_NUMBER=8 \
	-DNO_DEAD_GHOSTS \
	-DFORCE_BOMBS_NUMBER=4 \
	-DMEMORY_MAPPED \
	-DALT_DISPLAY_STATS \
	-DFLAT_ENEMIES \
	-DUSE_TINY_MEMORY_BUFFERS \
	--config $(CFG_PATH)/cc65/alt/vic20_unexpanded.cfg  \
	$(TINY_FILES) \
	$(CROSS_LIB_PATH)/memory/vic20_memory.s \
	$(CROSS_LIB_PATH)/sound/cc65/vic20/vic20_sounds_3k.c \
	$(CROSS_LIB_PATH)/display/init_graphics/cc65/vic20/vic20_init_graphics.c \
	$(CROSS_LIB_PATH)/display/alt_print/simple_alt_stats.c \
	-o $(BUILD_PATH)/ALT_TINY_vic20_unexpanded_turn_based.prg

