# ALTERNATIVE VERSIONS

# -----------------------------------------------------
# Z88DK


include z88dk_alternative_builds/Makefile.z88dk_alternative_builds_a-g

include z88dk_alternative_builds/Makefile.z88dk_alternative_builds_h-n

include z88dk_alternative_builds/Makefile.z88dk_alternative_builds_o-u

include z88dk_alternative_builds/Makefile.z88dk_alternative_builds_v-z


