#include "display_macros.h"

#include "tiles.h"

#include "init_images.h"


#define _CONST const

#if !defined(NO_COLOR)
    _CONST Image VERTICAL_HEAD_IMAGE = { _TILE_0, _SNAKE_COLOR };
    _CONST Image HORIZONTAL_HEAD_IMAGE = { _TILE_1, _SNAKE_COLOR };
    _CONST Image LEFT_MINE_IMAGE = {_TILE_2, COLOR_CYAN};
    _CONST Image RIGHT_MINE_IMAGE = {_TILE_3, COLOR_CYAN};
    _CONST Image BODY_IMAGE = { _TILE_4, _SNAKE_COLOR};
    _CONST Image APPLE_IMAGE = { _TILE_5, COLOR_RED };
    _CONST Image HI_TEXT_IMAGE = { _TILE_6, COLOR_RED };
    _CONST Image CENTRAL_BRICK_IMAGE = { _TILE_7, _WALL_COLOR };
    _CONST Image COIN_IMAGE = { _TILE_8, COLOR_WHITE };
    _CONST Image LV_TEXT_IMAGE = { _TILE_9, COLOR_GREEN };
    _CONST Image TRANSPARENT_BRICK_IMAGE = { _TILE_10, _WALL_COLOR };
    _CONST Image UP_MINE_IMAGE = { _TILE_11, COLOR_CYAN };
    _CONST Image VERTICAL_BRICK_IMAGE = { _TILE_12, _WALL_COLOR };
    _CONST Image HORIZONTAL_BRICK_IMAGE = { _TILE_13, _WALL_COLOR };
    _CONST Image SCORE_TEXT_LEFT_IMAGE = { _TILE_14, COLOR_CYAN };
    _CONST Image DOWN_MINE_IMAGE = { _TILE_15, COLOR_CYAN };
    _CONST Image SCORE_TEXT_RIGHT_IMAGE = { _TILE_16, COLOR_CYAN };
    _CONST Image MINE_IMAGE = { _TILE_17, COLOR_CYAN };
    _CONST Image SUPER_COIN_IMAGE = { _TILE_18, COLOR_CYAN };
    _CONST Image EXTRA_IMAGE = { _DOLLAR_TILE, COLOR_YELLOW };
#else
    _CONST Image VERTICAL_HEAD_IMAGE = { _TILE_0 };
    _CONST Image HORIZONTAL_HEAD_IMAGE = { _TILE_1 };
    _CONST Image LEFT_MINE_IMAGE = {_TILE_2};
    _CONST Image RIGHT_MINE_IMAGE = {_TILE_3};
    _CONST Image BODY_IMAGE = { _TILE_4};
    _CONST Image APPLE_IMAGE = { _TILE_5 };
    _CONST Image HI_TEXT_IMAGE = { _TILE_6 };
    _CONST Image CENTRAL_BRICK_IMAGE = { _TILE_7 };
    _CONST Image COIN_IMAGE = { _TILE_8 };
    _CONST Image LV_TEXT_IMAGE = { _TILE_9 };
    _CONST Image TRANSPARENT_BRICK_IMAGE = { _TILE_10 };
    _CONST Image UP_MINE_IMAGE = { _TILE_11 };
    _CONST Image VERTICAL_BRICK_IMAGE = { _TILE_12 };
    _CONST Image HORIZONTAL_BRICK_IMAGE = { _TILE_13 };
    _CONST Image SCORE_TEXT_LEFT_IMAGE = { _TILE_14 };
    _CONST Image DOWN_MINE_IMAGE = { _TILE_15 };
    _CONST Image SCORE_TEXT_RIGHT_IMAGE = { _TILE_16 };
    _CONST Image MINE_IMAGE = { _TILE_17 };
    _CONST Image SUPER_COIN_IMAGE = { _TILE_18 };
    _CONST Image EXTRA_IMAGE = { _DOLLAR_TILE };
#endif




