#ifndef _INIT_IMAGES_H
#define _INIT_IMAGES_H

#include "tiles.h"

#define _SNAKE_COLOR _XL_GREEN

#define _WALL_COLOR _XL_YELLOW


#if defined(NO_CONST_IMAGES)
    void INIT_IMAGES();
#else
    #define INIT_IMAGES()
#endif

#define VERTICAL_HEAD_TILE  _TILE_0
#define HORIZONTAL_HEAD_TILE _TILE_1
#define LEFT_MINE_TILE _TILE_2
#define RIGHT_MINE_TILE _TILE_3
#define BODY_TILE _TILE_4
#define APPLE_TILE _TILE_5
#define HI_TEXT_TILE _TILE_6
#define CENTRAL_BRICK_TILE _TILE_7
#define RING_TILE _TILE_8
#define LV_TEXT_TILE _TILE_9
#define TRANSPARENT_BRICK_TILE _TILE_10
#define UP_MINE_TILE _TILE_11
#define VERTICAL_BRICK_TILE _TILE_12
#define HORIZONTAL_BRICK_TILE _TILE_13
#define SCORE_TEXT_LEFT_TILE _TILE_14
#define DOWN_MINE_TILE _TILE_15
#define SCORE_TEXT_RIGHT_TILE _TILE_16
#define MINE_TILE _TILE_17
#define SUPER_RING_TILE _TILE_18
#define EXTRA_TILE _DOLLAR_TILE




#endif // _INIT_IMAGES_H

