############################

C128_Z80_80COL_GAME_OPTS      = -DNO_LEVEL_END 

ZX81_GFX_GAME_OPTS            = -DNO_LEVEL_END

PHC25_GAME_OPTS               = -DNO_LEVEL_END -DNO_LETTER_VALUES -DNO_DISPLAY_BORDERS -D_XL_NO_SOUND

PHC25_MONO_GAME_OPTS          = -DNO_LEVEL_END -DNO_LETTER_VALUES -DNO_DISPLAY_BORDERS -D_XL_NO_SOUND