;
; File generated by cc65 v 2.17 - Git d002f6e
;
	.fopt		compiler,"cc65 v 2.17 - Git d002f6e"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_gotoxy
	.import		_cputc
	.export		__draw
	.export		_DRAW_BROKEN_WALL
	.export		__blink_draw
	.export		__delete
	.export		_DRAW_HORIZONTAL_LINE
	.export		_DRAW_VERTICAL_LINE
	.export		_INIT_IMAGES
	.export		_INIT_GRAPHICS
	.export		_PLAYER_IMAGE
	.export		_GHOST_IMAGE
	.export		_DEAD_GHOST_IMAGE
	.export		_BOMB_IMAGE
	.export		_POWERUP_IMAGE
	.export		_BULLET_IMAGE
	.export		_GUN_IMAGE
	.export		_EXTRA_POINTS_IMAGE
	.export		_SKULL_IMAGE
	.export		_LEFT_ENEMY_MISSILE_IMAGE
	.export		_RIGHT_ENEMY_MISSILE_IMAGE
	.export		_ROCKET_IMAGE
	.export		_FREEZE_IMAGE
	.export		_EXTRA_LIFE_IMAGE
	.export		_INVINCIBILITY_IMAGE
	.export		_CHASE_IMAGE
	.export		_SUPER_IMAGE
	.export		_CONFUSE_IMAGE
	.export		_ZOMBIE_IMAGE
	.export		_BROKEN_WALL_IMAGE

.segment	"BSS"

_PLAYER_IMAGE:
	.res	1,$00
_GHOST_IMAGE:
	.res	1,$00
_DEAD_GHOST_IMAGE:
	.res	1,$00
_BOMB_IMAGE:
	.res	1,$00
_POWERUP_IMAGE:
	.res	1,$00
_BULLET_IMAGE:
	.res	1,$00
_GUN_IMAGE:
	.res	1,$00
_EXTRA_POINTS_IMAGE:
	.res	1,$00
_SKULL_IMAGE:
	.res	1,$00
_LEFT_ENEMY_MISSILE_IMAGE:
	.res	1,$00
_RIGHT_ENEMY_MISSILE_IMAGE:
	.res	1,$00
_ROCKET_IMAGE:
	.res	1,$00
_FREEZE_IMAGE:
	.res	1,$00
_EXTRA_LIFE_IMAGE:
	.res	1,$00
_INVINCIBILITY_IMAGE:
	.res	1,$00
_CHASE_IMAGE:
	.res	1,$00
_SUPER_IMAGE:
	.res	1,$00
_CONFUSE_IMAGE:
	.res	1,$00
_ZOMBIE_IMAGE:
	.res	1,$00
_BROKEN_WALL_IMAGE:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ _draw (unsigned char, unsigned char, __near__ struct ImageStruct *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$02
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DRAW_BROKEN_WALL (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DRAW_BROKEN_WALL: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	adc     #$02
	jsr     _gotoxy
	lda     _BROKEN_WALL_IMAGE
	jsr     _cputc
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ _blink_draw (unsigned char, unsigned char, __near__ struct ImageStruct *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__blink_draw: near

.segment	"CODE"

	jsr     pushax
	ldy     #$05
	lda     (sp),y
	jsr     pusha
	ldy     #$05
	lda     (sp),y
	clc
	adc     #$02
	jsr     _gotoxy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	beq     L004A
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	jsr     _cputc
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	jmp     L0072
L004A:	lda     #$20
	jsr     _cputc
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$01
L0072:	ldy     #$00
	sta     (ptr1),y
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ _delete (unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	__delete: near

.segment	"CODE"

	jsr     pusha
	ldy     #$01
	lda     (sp),y
	jsr     pusha
	ldy     #$01
	lda     (sp),y
	clc
	adc     #$02
	jsr     _gotoxy
	lda     #$20
	jsr     _cputc
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ DRAW_HORIZONTAL_LINE (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DRAW_HORIZONTAL_LINE: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$02
	jsr     _gotoxy
	lda     #$00
	tay
L0073:	sta     (sp),y
	iny
	cmp     (sp),y
	bcs     L0068
	lda     #$2D
	jsr     _cputc
	ldy     #$00
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0073
L0068:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ DRAW_VERTICAL_LINE (unsigned char, unsigned char, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_DRAW_VERTICAL_LINE: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp1
	lda     #$00
	tay
L0075:	sta     (sp),y
	iny
	cmp     (sp),y
	bcs     L0057
	ldy     #$03
	lda     (sp),y
	jsr     pusha
	ldy     #$03
	lda     (sp),y
	clc
	adc     #$02
	sta     ptr1
	ldy     #$01
	lda     (sp),y
	clc
	adc     ptr1
	jsr     _gotoxy
	lda     #$DD
	jsr     _cputc
	ldy     #$00
	clc
	lda     #$01
	adc     (sp),y
	jmp     L0075
L0057:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ INIT_IMAGES (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_INIT_IMAGES: near

.segment	"CODE"

	lda     #$D8
	sta     _BOMB_IMAGE
	lda     #$4F
	sta     _GHOST_IMAGE
	lda     #$2A
	sta     _PLAYER_IMAGE
	lda     #$2B
	sta     _SKULL_IMAGE
	lda     #$24
	sta     _EXTRA_POINTS_IMAGE
	lda     #$D3
	sta     _POWERUP_IMAGE
	lda     #$21
	sta     _GUN_IMAGE
	lda     #$2E
	sta     _BULLET_IMAGE
	lda     #$23
	sta     _DEAD_GHOST_IMAGE
	lda     #$3E
	sta     _LEFT_ENEMY_MISSILE_IMAGE
	lda     #$3C
	sta     _RIGHT_ENEMY_MISSILE_IMAGE
	lda     #$5E
	sta     _ROCKET_IMAGE
	lda     #$C6
	sta     _FREEZE_IMAGE
	lda     _PLAYER_IMAGE
	sta     _EXTRA_LIFE_IMAGE
	lda     #$D6
	sta     _INVINCIBILITY_IMAGE
	lda     #$C8
	sta     _SUPER_IMAGE
	lda     #$C3
	sta     _CONFUSE_IMAGE
	lda     #$DA
	sta     _ZOMBIE_IMAGE
	lda     #$D8
	sta     _BROKEN_WALL_IMAGE
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ INIT_GRAPHICS (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_INIT_GRAPHICS: near

.segment	"CODE"

	rts

.endproc

