
#ifndef _ATARI_MODE1_REDEFINED_CHARS_SETTINGS
#define _ATARI_MODE1_REDEFINED_CHARS_SETTINGS

#define _ATARI_MODE1_RED 0
#define _ATARI_MODE1_WHITE	64
#define _ATARI_MODE1_BLUE 128
#define _ATARI_MODE1_YELLOW 192

#define _PLAYER_DOWN (60 + _ATARI_MODE1_BLUE)
#define _PLAYER_UP (61 + _ATARI_MODE1_BLUE)
#define _PLAYER_RIGHT (62 + _ATARI_MODE1_BLUE)
#define _PLAYER_LEFT (63 + _ATARI_MODE1_BLUE)

#define _EXTRA_LIFE (60 + _ATARI_MODE1_YELLOW)

#define _GHOST (59 + _ATARI_MODE1_WHITE)

#define _DEAD_GHOST (59 + _ATARI_MODE1_RED)

#define _SKULL (30 + _ATARI_MODE1_YELLOW)
#define _BOMB (29+ _ATARI_MODE1_RED)

#define _POWERUP (28 + _ATARI_MODE1_YELLOW)
#define _FREEZE (28 + _ATARI_MODE1_BLUE)
#define _SUPER (28 + _ATARI_MODE1_RED)

#define _CONFUSE (30 + _ATARI_MODE1_RED)

#define _GUN (11 + _ATARI_MODE1_YELLOW)
#define _BULLET (10 + _ATARI_MODE1_RED)

#define _INVINCIBILITY (12 + _ATARI_MODE1_YELLOW)

#define _LEFT_HORIZONTAL_MISSILE (9 + _ATARI_MODE1_WHITE)
#define _RIGHT_HORIZONTAL_MISSILE (8 + _ATARI_MODE1_WHITE)	
#define _ROCKET (7 + _ATARI_MODE1_WHITE)

#define _EXTRA_POINTS (4 + _ATARI_MODE1_YELLOW)
#define _VERTICAL_BRICK (5 + _ATARI_MODE1_YELLOW)
#define _HORIZONTAL_BRICK (6 + _ATARI_MODE1_YELLOW)

#define _SPACE ' '
#define _BROKEN_WALL _BOMB

#endif // _ATARI_MODE1_REDEFINED_CHARS_SETTINGS
