#ifndef _IMAGES_H
#define _IMAGES_H

#include "cross_lib.h"

Image VERTICAL_HEAD_IMAGE;  
Image HORIZONTAL_HEAD_IMAGE; 
Image RIGHT_HEAD_IMAGE; 
Image LEFT_HEAD_IMAGE; 	


Image VERTICAL_BODY_IMAGE; 
Image BOTTOM_TAIL_IMAGE; 

Image DEAD_GHOST_IMAGE; 

Image SKULL_IMAGE; 

Image CALM_DOWN_IMAGE; 
Image HORIZONTAL_JOINT_IMAGE; 
Image FIRE_POWER_IMAGE; 
Image EXTRA_POINTS_IMAGE; 

Image BULLET_IMAGE; 

Image VERTICAL_BRICK_IMAGE; 
Image HORIZONTAL_BRICK_IMAGE; 

Image LEFT_TAIL_IMAGE; 

Image RIGHT_TAIL_IMAGE; 

Image VERTICAL_JOINT_IMAGE; 

Image BOTTOM_HEAD_IMAGE; 
Image SUPER_IMAGE; 

Image EXTRA_LIFE_IMAGE; 
Image INVINCIBILITY_IMAGE; 


Image CONFUSE_IMAGE; 
Image SUICIDE_IMAGE; 

Image BROKEN_BRICK_IMAGE; 
    
Image TOP_HEAD_IMAGE; 
Image TOP_HEAD_JOINT_IMAGE; 
Image BOTTOM_HEAD_JOINT_IMAGE; 
Image LEFT_HEAD_JOINT_IMAGE; 
Image RIGHT_HEAD_JOINT_IMAGE; 
Image TOP_TAIL_IMAGE; 



#endif // _IMAGES_H

