'\" t
.\"     srecord - The "srecord" program.
.\"     Copyright (C) 2007-2009, 2011 Peter Miller
.\"
.\"     This program is free software; you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation; either version 3 of the License, or
.\"     (at your option) any later version.
.\"
.\"     This program is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\"
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program. If not, see
.\"     <http://www.gnu.org/licenses/>.
.\"
.ds n) srec_ti_txt
.TH srec_ti_txt 5 SRecord "Reference Manual"
.SH NAME
srec_ti_txt \- Texas Instruments ti\[hy]txt (MSP430) file format
.if require_index \{
.XX "srec_ti_txt(5)" "Texas Instruments ti\[hy]txt (MSP430) file format"
.\}
.SH DESCRIPTION
The ti\[hy]TXT format is used by the Texas Instruments MSP430 familty
programming adapter.
.PP
The TI\[hy]TXT hex format supports 16\[hy]bit hexadecimal data.  It consists of
one or more sections, followed by the end\[hy]of\[hy]file indicator.
.PP
Each section consistes of an at (@) sign followed a execution start address (in
hexadecimal), and newline, and then data bytes (in hexadecimal).  The
section address is followed by a newline.
There are to be 16 data bytes per line,
except for the last line in a section.
.PP
The end\[hy]of\[hy]file indicator is the letter \f[CW]q\fP
followed by a newline.
The end\[hy]of\[hy]file indicator mandatory.
.SS Size Multiplier
In general, binary data will expand in sized by approximately 3.0 times
when represented with this format.
.SH EXAMPLE
Here is an example ti\[hy]txt file taken from the reference below:
.RS
.ft CW
.nf
@F000
31 40 00 03 B2 40 80 5A 20 01 D2 D3 22 00 D2 E3
21 00 3F 40 E8 FD 1F 83 FE 23 F9 3F
@FFFE
00 F0
q
.ft P
.fi
.RE
.br
.ne 1i
.SH SEE ALSO
http://www.ti.com/lit/pdf/slau101, section A.2.
\f[B]Note:\fP the portion which says addresses must be even, and the
number of data bytes in a section must be even, is wrong.
.so man/man1/z_copyright.so
.\" vim: set ts=8 sw=4 et :
