* 6809 assembly program generated by cmoc 0.1.56


	SECTION	code


_udgs	EXPORT


	ENDSECTION




	SECTION	rodata


string_literals_start	EQU	*
string_literals_end	EQU	*


*******************************************************************************

* READ0ONLY GLOBAL VARIABLES


	ENDSECTION




	SECTION	rwdata


* Globals with static initializers
_udgs	EQU	*		udgs: uint8_t[]



	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000

; invincibility
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 192 
    FCB 32 
    FCB 80 
    FCB 144 
    FCB 0


; left missile
    FCB $2A 
    FCB $2A 
    FCB $2A 
    FCB $3A 
    FCB $2A 
    FCB $2A 
    FCB $2A 
    FCB $00


; bullet
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 3 
    FCB 4 
    FCB 10 
    FCB 9 
    FCB 0


; dollar $
    FCB $18 
    FCB $3e 
    FCB $60 
    FCB $3c 
    FCB $06 
    FCB $7c 
    FCB $18 
    FCB $00


; power-up F
    FCB 2 
    FCB 7 
    FCB 2 
    FCB 2 
    FCB 2 
    FCB 2 
    FCB 2 
    FCB 5


; vertical brick
    FCB 32 
    FCB 112 
    FCB 32 
    FCB 252 
    FCB 34 
    FCB 37 
    FCB 249 
    FCB 80


; skull
    FCB 24 
    FCB  36 
    FCB  24 
    FCB   0 
    FCB 153 
    FCB   0 
    FCB  36 
    FCB 36


; ghost
    FCB 153 
    FCB  24 
    FCB  36 
    FCB 36 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0


; bomb
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 24 
    FCB  36


; player down
    FCB 24 
    FCB  36 
    FCB  24 
    FCB 102 
    FCB 153 
    FCB  24 
    FCB  36 
    FCB 36


; horizontal brick
    FCB 0 
    FCB   0 
    FCB   0 
    FCB 63 
    FCB 64 
    FCB 160 
    FCB 159 
    FCB 0


; power-up S
    FCB 60 
    FCB 126 
    FCB 231 
    FCB 195 
    FCB 195 
    FCB 231 
    FCB 126 
    FCB 60


	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00000000
	FCB %00111110
	FCB %00000000
	FCB %00000000
	FCB %00000000

; right missile
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 74 
    FCB 100 
    FCB 0


; rocket
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 252 
    FCB 2 
    FCB 5 
    FCB 249 
    FCB 0


	FCB %00000000 ; 
	FCB %00111100 ;  ####
	FCB %01000110 ; #   ## 
	FCB %01001010 ; #  # # 
	FCB %01010010 ; # #  # 
	FCB %01100010 ; ##   #
	FCB %00111100 ;  ####
	FCB %00000000

    FCB 90 
    FCB 36 
    FCB  24 
    FCB 102 
    FCB 153 
    FCB  24 
    FCB  36 
    FCB 36

    FCB 0 
    FCB 0 
    FCB 90 
    FCB 36 
    FCB  24 
    FCB 102 
    FCB 89 
    FCB  24

    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 90 
    FCB 36 
    FCB  24 
    FCB 102

    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 90 
    FCB 36

    FCB 8 
    FCB 42 
    FCB 28 
    FCB 119 
    FCB 28 
    FCB 42 
    FCB 8 
    FCB 0

    FCB 240 
    FCB 240 
    FCB 255 
    FCB 133 
    FCB 255 
    FCB 161 
    FCB 255 
    FCB 0


	FCB %00000000
	FCB %01111110
	FCB %00000010
	FCB %00000100
	FCB %00001000
	FCB %00010000
	FCB %00010000
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111100
	FCB %00000000

	FCB %00000000
	FCB %00111100
	FCB %01000010
	FCB %01000010
	FCB %00111110
	FCB %00000010
	FCB %00111100
	FCB %00000000

; dead ghost
    FCB 24 
    FCB 102 
    FCB 154 
    FCB  24 
    FCB  36 
    FCB 36 
    FCB 0 
    FCB 0


; power-up H
    FCB 32 
    FCB 112 
    FCB 32 
    FCB 32 
    FCB 32 
    FCB 32 
    FCB 32 
    FCB 80


; player up
    FCB 0 
    FCB 0 
    FCB 24 
    FCB  36 
    FCB  24 
    FCB 102 
    FCB 89 
    FCB  24


; player right
    FCB 36 
    FCB 36 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0


; player left
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 0 
    FCB 24 
    FCB  36 
    FCB  24 
    FCB 102


; gun
    FCB 2 
    FCB 7 
    FCB 2 
    FCB 63 
    FCB 66 
    FCB 162 
    FCB 159 
    FCB 5






	ENDSECTION




	SECTION	bss


* Uninitialized globals
bss_start	EQU	*
bss_end	EQU	*


	ENDSECTION




	SECTION	code




	ENDSECTION




	SECTION	initgl




*******************************************************************************

* Initialize global variables.


	ENDSECTION




*******************************************************************************

* Importing 0 utility routine(s).


*******************************************************************************

	END





