#########################################################
# (FAST) SIMPLE TESTS

include ./makefiles.common/auxiliary/Makefile_compilers

include ./games/chase/Makefile.chase


#######################################################
# (LONG) TESTS
# Compilers and Dev-kits covered:
# - gcc

simple_test: gcc_buffered


#######################################################
# TESTS EXCLUDING Z88DK
# Compilers and Dev-kits covered:
# - gcc
# - cmoc
# - cc65
# - ack
# - gcc_amiga
# - gcc_atari_st
# - xtc68
# - lcc1802

no_z88dk_test: \
    gcc_full_tests \
    cc65_full_tests \
    cmoc_full_tests \
    ack_full_tests \
    lcc1802_full_tests \
    mod_gcc_full_tests \
    xtc68_full_tests 

    

mod_gcc_full_tests: \
    gcc_amiga_targets \
    gcc_atari_st_targets \

xtc68_full_tests: \
    xtc68_targets


cmoc_full_tests: \
    coco_targets

# to fix
#     oric_targets 
#     gamate_targets 
cc65_full_tests: \
    vic20_targets \
    supervision_targets \
    atari_targets \
    atari_lynx_targets \
    creativision_targets \
    pet_targets \
    c64_targets \

ack_full_tests: \
    pc8086_targets \
    cpm_8080_adm3a 
    
gcc_full_tests: \
    simple_test \
    ncurses

lcc1802_full_tests: \
    comx



#######################################################
# (LONG) TESTS
# Compilers and Dev-kits covered:
# - gcc
# - cmoc
# - cc65
# - ack
# - gcc_amiga
# - gcc_atari_st
# - xtc68
# - lcc1802
# - z88dk 

.PHONY: test z88dk_test

#     tiki100 
z88dk_test: \
    aquarius_exp_4k \
    c128_z80_80col \
    cpc \
    cpm_z80_adm3a \
    gal_6k \
    msx_32k_rom \
    spectrum_48k \
    zx81_32k_wrx_turn_based 

test:
	make z88dk_test
	make no_z88dk_test 






####################################################################################################################
# Z88DK Compilation Tests with several minimal versions of the game
# 
# include makefiles.other/chase/tests/Makefile.z88dk_quick_tests


