####################################################################################################################
# CROSS CHASE (default game)

include Makefile.chase

####################################################################################################################
# DEBUG	

# - Z88DK
#include makefiles.common/debug/Makefile.cc65_debug

# - CC65
#include makefiles.common/debug/Makefile.z88dk_debug

# - LCC1802
include makefiles.common/debug/Makefile.lcc1802_debug

