# ------------------------------------------------------------------------------------------
# Z88DK
#

Z88DK_PATH ?= /cygdrive/c/z88dk/bin/
Z88DK_PATH_20171210 ?= /cygdrive/c/z88dk_20171210/bin/
Z88DK_INCLUDE ?= /cygdrive/c/z88dk/include

MYZ88DK ?= zcc$(EXEEXT)
MYZ88DKASM ?= z80asm$(EXEEXT)


SCCZ80_OPTS ?= -O0
#-O3

ZSDCC_OPTS ?= -SO0
# -SO3 --max-allocs-per-node200000


################################################################################

# missing: abc800, xo7, c7420, rex
# missing 8080: m100
z88dk_targets:
	make z88dk_targets_a-c \
	make z88dk_targets_d-k \
	make z88dk_targets_l-m \
	make z88dk_targets_o-p \
	make z88dk_targets_q-s \
	make z88dk_targets_t-v \
	make z88dk_targets_w-z



##################################################################

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_a-c

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_d-k

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_l-m

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_n-p

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_q-s

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_t-v

include makefiles/targets/makefiles_z88dk/Makefile_z88dk_w-z


# ----------------------------------------------------------------

