#include "cpc_sounds.h"

#include "cpcrslib.h"
#include "cpcwyzlib.h"
	
extern unsigned char SONG_TABLE[];
extern unsigned char EFFECT_TABLE[];
extern unsigned char RULE_TABLE[];
extern unsigned char SOUND_TABLE[];


void _ping_sound(unsigned char freq)
{
	cpc_DisableFirmware();
	cpc_WyzInitPlayer(SOUND_TABLE, RULE_TABLE, EFFECT_TABLE, SONG_TABLE);	
	cpc_WyzSetPlayerOn();	
	cpc_WyzStartEffect(0,0);
	cpc_WyzSetPlayerOff();	
	cpc_EnableFirmware();	
}


void _explosion_sound(unsigned char freq)
{
	cpc_DisableFirmware();	
	cpc_WyzInitPlayer(SOUND_TABLE, RULE_TABLE, EFFECT_TABLE, SONG_TABLE);	
	cpc_WyzSetPlayerOn();	
	cpc_WyzStartEffect(1,1);
	cpc_WyzSetPlayerOff();	
	cpc_EnableFirmware();		
}


void ZAP_SOUND(void)
{
	cpc_DisableFirmware();	
	cpc_WyzInitPlayer(SOUND_TABLE, RULE_TABLE, EFFECT_TABLE, SONG_TABLE);	
	cpc_WyzSetPlayerOn();	
	cpc_WyzStartEffect(2,2);
	cpc_WyzSetPlayerOff();	
	cpc_EnableFirmware();		
}




#asm

._SONG_TABLE 
	DEFW _SONG_0
	
._SONG_0 DEFB	42
//BINARY "Wyazow.mus"			//Song file to be included


._RULE_TABLE
defw _PAUTA_1,_PAUTA_2,_PAUTA_3,_PAUTA_4,_PAUTA_5,_PAUTA_6,_PAUTA_7

// from *.mus.asm file generated by WYZTracker:

._PAUTA_1	DEFB	46,0,13,0,12,0,11,0,10,0,9,0,128+1
._PAUTA_2	DEFB	8,0,74,0,11,0,43,0,10,0,9,0,8,0,7,0,$40+6,0,6,0,$20+6,0,6,0,132
._PAUTA_3	DEFB	6,0,71,0,8,0,40,0,8,0,71,0,$40+4,0,4,0,$20+4,0,4,0,132
._PAUTA_4	DEFB	77,0,12,0,12,0,11,0,11,0,11,0,10,0,9,0,8,-1,8,0,8,0,8,1,8,1,8,0,8,0,8,-1,128+8
._PAUTA_5	DEFB	75,0,10,0,9,0,9,0,8,0,8,-1,8,0,8,0,8,1,8,1,8,0,8,0,8,-1,128+8
._PAUTA_6	DEFB	5,0,70,0,7,0,38,0,5,0,3,0,129
._PAUTA_7	DEFB	71,0,6,0,5,0,5,0,5,0,4,0,129




._SOUND_TABLE
		defw _SONIDO1
		defw _SONIDO2
		defw _SONIDO3
		defw _SONIDO4
		defw _SONIDO5


// from *.mus.asm file generated by WYZTracker:

._SONIDO1	DEFB	209,63,0,69,173,0,255
._SONIDO2	DEFB	93,47,0,209,14,11,255
._SONIDO3	DEFB	0,11,1,255
._SONIDO4	DEFB	186,57,0,0,102,0,162,131,0,255
._SONIDO5	DEFB	0,12,14,255




._EFFECT_TABLE
		defw _EFECTO0
		defw _EFECTO1
		defw _EFECTO2
		defw _EFECTO3


._EFECTO0                

defb $58,$0D
defb $50,$0B
defb $47,$0A
defb $3E,$06
defb $35,$03
defb $50,$09
defb $47,$0A
defb $3E,$07
defb $FF

._EFECTO1                

defb $58,$0C
defb $5D,$0D
defb $61,$0E
defb $66,$0F
defb $6A,$0E
defb $6F,$0D
defb $7A,$0C
defb $78,$0B
defb $7C,$0A
defb $85,$09
defb $8E,$08
defb $97,$07
defb $A0,$06
defb $A9,$05
defb $FF


._EFECTO2               

defb $1F,$0B
defb $1A,$0C
defb $1F,$0D
defb $16,$0E
defb $1F,$0E
defb $0D,$0D
defb $1F,$0C
defb $0D,$0B
defb $00,$00
defb $00,$00
defb $1F,$08
defb $1A,$09
defb $1F,$0A
defb $16,$0B
defb $1F,$0B
defb $0D,$0A
defb $1F,$09
defb $0D,$07
defb $00,$00
defb $00,$00
defb $1F,$06
defb $1A,$07
defb $1F,$08
defb $16,$08
defb $1F,$07
defb $0D,$06
defb $1F,$05
defb $FF

._EFECTO3                

defb $1A,$0E
defb $1A,$0E
defb $00,$00
defb $1A,$0A
defb $1A,$0A
defb $00,$00
defb $1A,$0C
defb $1A,$0C
defb $00,$00
defb $1A,$08
defb $1A,$08
defb $FF




#endasm