#ifndef _INIT_IMAGES_H
#define _INIT_IMAGES_H


#define _PLAYER_COLOR _XL_CYAN
#define _GHOST_COLOR _XL_WHITE
#define _DEAD_GHOST_COLOR _XL_RED
#define _SKULL_COLOR _XL_YELLOW
#define _BOMB_COLOR _XL_RED
#define _MISSILE_COLOR _XL_WHITE
#define _ROCKET_COLOR _XL_WHITE
#define _CALM_DOWN_COLOR _XL_GREEN
#define _FIRE_CHARGE_COLOR _XL_GREEN
#define _FREEZE_COLOR _XL_CYAN
#define _SUPER_COLOR _XL_RED
#define _GUN_COLOR _XL_YELLOW
#define _BULLET_COLOR _XL_WHITE
#define _BRICK_COLOR _XL_GREEN
#define _BROKEN_BRICK_COLOR _XL_YELLOW
#define _EXTRA_POINTS_COLOR _XL_YELLOW
#define _EXTRA_LIFE_COLOR _XL_WHITE
#define _INVINCIBILITY_COLOR _XL_YELLOW
#define _CONFUSE_COLOR _XL_RED
#define _SUICIDE_COLOR _XL_YELLOW




void INIT_IMAGES(void);




#endif // _INIT_IMAGES_H

